# Generated by Django 6.0.6 on 2026-06-23 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('categorie', models.CharField(choices=[('AGREMENT', 'Agrement'), ('AUTORISATION', 'Autorisation environnementale'), ('CONTRAT', 'Contrat'), ('RAPPORT', 'Rapport'), ('DECLARATION', 'Declaration'), ('CORRESPONDANCE', 'Correspondance officielle'), ('JURIDIQUE', 'Document juridique'), ('TECHNIQUE', 'Document technique'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20)),
                ('fichier', models.FileField(upload_to='archive/%Y/%m/')),
                ('nom_original', models.CharField(blank=True, max_length=300)),
                ('taille', models.PositiveIntegerField(default=0)),
                ('type_mime', models.CharField(blank=True, max_length=100)),
                ('tags', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_archives', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
