# Generated by Django 6.0.6 on 2026-06-23 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recuperateurs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_inspection', models.CharField(choices=[('ROUTINE', 'Contrôle de routine'), ('SURPRISE', 'Contrôle inopiné'), ('PLAINTE', 'Suite à plainte'), ('SUIVI', 'Contrôle de suivi')], max_length=15)),
                ('date_inspection', models.DateField()),
                ('resultat', models.CharField(blank=True, choices=[('CONFORME', 'Conforme'), ('NON_CONFORME', 'Non conforme'), ('EN_COURS', "En cours d'examen")], max_length=15)),
                ('pv_numero', models.CharField(blank=True, max_length=50)),
                ('pv_type', models.CharField(blank=True, max_length=50)),
                ('observations', models.TextField(blank=True)),
                ('actions_correctives', models.TextField(blank=True)),
                ('delai_regularisation', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inspecteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('recuperateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='recuperateurs.recuperateur')),
            ],
            options={
                'ordering': ['-date_inspection'],
            },
        ),
    ]
