# Generated by Django 6.0.6 on 2026-06-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_operateur', models.CharField(choices=[('GENERATEUR', 'Générateur de déchets'), ('TRANSPORTEUR', 'Transporteur de déchets'), ('ELIMINATEUR', 'Éliminateur de déchets'), ('VALORISATEUR', 'Valorisateur de déchets'), ('CET', "Centre d'Enfouissement Technique")], max_length=20)),
                ('raison_sociale', models.CharField(max_length=300)),
                ('nin', models.CharField(blank=True, max_length=50)),
                ('nif', models.CharField(blank=True, max_length=50)),
                ('nis', models.CharField(blank=True, max_length=50)),
                ('registre_commerce', models.CharField(blank=True, max_length=100)),
                ('secteur_activite', models.CharField(blank=True, max_length=200)),
                ('wilaya', models.CharField(blank=True, max_length=3)),
                ('commune', models.CharField(blank=True, max_length=200)),
                ('adresse', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('num_agrement', models.CharField(blank=True, max_length=100)),
                ('date_agrement', models.DateField(blank=True, null=True)),
                ('duree_agrement', models.IntegerField(blank=True, null=True)),
                ('date_debut_agrement', models.DateField(blank=True, null=True)),
                ('date_fin_agrement', models.DateField(blank=True, null=True)),
                ('type_engins', models.CharField(blank=True, max_length=200)),
                ('immatriculation', models.CharField(blank=True, max_length=100)),
                ('nom_conducteur', models.CharField(blank=True, max_length=200)),
                ('codes_dechets_autorises', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif'), ('SUSPENDU', 'Suspendu')], default='ACTIF', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Opérateur',
                'ordering': ['type_operateur', 'raison_sociale'],
            },
        ),
    ]
