# Generated by Django 4.2.13 on 2026-07-01 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operateurs', '0004_assigner_operateurs_existants'),
    ]

    operations = [
        migrations.AddField(
            model_name='operateur',
            name='convention_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operateur',
            name='convention_duree',
            field=models.IntegerField(blank=True, help_text='Durée en années', null=True),
        ),
        migrations.AddField(
            model_name='operateur',
            name='convention_numero',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
