# Generated by Django 4.2.13 on 2026-06-24 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traceability', '0002_copy_data_from_operations'),
    ]

    operations = [
        migrations.AddField(
            model_name='traceability',
            name='couleur',
            field=models.CharField(blank=True, choices=[('TRANSPARENT', 'Transparent'), ('BLANC', 'Blanc'), ('NOIR', 'Noir'), ('BLEU', 'Bleu'), ('VERT', 'Vert'), ('ROUGE', 'Rouge'), ('JAUNE', 'Jaune'), ('GRIS', 'Gris'), ('MARRON', 'Marron'), ('MULTICOLORE', 'Multicolore')], max_length=20),
        ),
        migrations.AddField(
            model_name='traceability',
            name='niveau_proprete',
            field=models.CharField(blank=True, choices=[('TRES_PROPRE', 'Très propre'), ('PROPRE', 'Propre'), ('MOYENNEMENT_PROPRE', 'Moyennement propre'), ('SALE', 'Sale'), ('TRES_SALE', 'Très sale')], max_length=25, verbose_name='Niveau de propreté'),
        ),
    ]
