# Generated by Django 4.2.13 on 2026-07-01 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traceability', '0004_traceability_cet_traceability_quantite_enfouie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traceability',
            name='repartitions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='traceability',
            name='destination_type',
            field=models.CharField(choices=[('VALORISATION', 'Valorisation'), ('ELIMINATION', 'Élimination (DSD)'), ('STOCKAGE', 'Stockage temporaire'), ('RECYCLAGE', 'Recyclage'), ('CET', "Centre d'Enfouissement Technique"), ('MULTIPLE', 'Multi-destinations')], default='VALORISATION', max_length=20),
        ),
    ]
