# Generated by Django 4.2.13 on 2026-07-02 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traceability', '0005_add_repartitions'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('last_value', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': "Compteur d'opération",
                'verbose_name_plural': "Compteurs d'opération",
            },
        ),
        migrations.AlterField(
            model_name='traceability',
            name='statut',
            field=models.CharField(choices=[('EN_COURS', 'En cours'), ('ENLEVEMENT', "En cours d'enlèvement"), ('TRANSPORT', 'En transport'), ('RECEPTION', 'Réceptionné'), ('TRAITEMENT', 'En traitement'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], default='EN_COURS', max_length=15),
        ),
    ]
