# Generated by Django 4.2.13 on 2026-07-02 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traceability', '0006_operationcounter_alter_traceability_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='traceability',
            name='frais_transport_ttc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Frais de transport TTC (DZD)'),
        ),
        migrations.AddField(
            model_name='traceability',
            name='prix_achat_ttc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name="Prix d'achat TTC (DZD)"),
        ),
    ]
