# Generated by Django 4.2.13 on 2026-07-02 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traceability', '0007_traceability_frais_transport_ttc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traceability',
            name='prix_unitaire_ttc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Prix unitaire TTC (DZD)'),
        ),
        migrations.AlterField(
            model_name='traceability',
            name='prix_achat_ttc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name="Prix d'achat total TTC (DZD)"),
        ),
    ]
