# Generated by Django 4.2.13 on 2026-07-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traceability', '0008_traceability_prix_unitaire_ttc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traceability',
            name='autres_frais_ttc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Autres frais TTC (DZD)'),
        ),
    ]
