# Generated by Django 4.2.13 on 2026-07-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traceability', '0009_traceability_autres_frais_ttc'),
    ]

    operations = [
        migrations.AddField(
            model_name='traceability',
            name='prix_revient_global_ttc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Prix de revient global TTC (DZD)'),
        ),
        migrations.AddField(
            model_name='traceability',
            name='prix_revient_unitaire_ttc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Prix de revient unitaire TTC (DZD)'),
        ),
    ]
