"""
Seed the Nomenclature model from the frontend nomenclatureData.js
Ensures the AI assistant has the same data as the nomenclature page.
Usage: python seed_from_frontend.py
"""
import os, django, re
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings')
django.setup()

from apps.nomenclature.models import Nomenclature

# ── Data from nomenclatureData.js (208 codes) ───────────────────────────────
# Format: (code, famille, nom_fr, classe, danger_fr)
DATA = [
    ('1.3.1','1','Déchets de graviers et débris de pierres','I',''),
    ('1.3.2','1','Déchets de sable et d\'argile','I',''),
    ('1.3.3','1','Déchets provenant de la taille et du sciage des pierres','I',''),
    ('1.3.99','1','Déchets non spécifiés','I',''),
    ('1.4.1','1','Boues et autres déchets de forage contenant de l\'eau douce','I',''),
    ('1.4.99','1','Déchets non spécifiés','I',''),
    ('2.1.1','2','Déchets de tissus végétaux','MA',''),
    ('2.1.2','2','Déchets de matières plastiques','MA',''),
    ('2.1.99','2','Déchets non spécifiés','MA',''),
    ('2.4.1','2','Terre provenant du lavage et du nettoyage des betteraves','MA',''),
    ('2.4.99','2','Déchets non spécifiés','MA',''),
    ('2.7.1','2','Déchets provenant du lavage, du nettoyage et de la réduction mécanique des matières premières','MA',''),
    ('2.7.2','2','Matières impropres à la consommation ou à la transformation','MA',''),
    ('2.7.99','2','Déchets non spécifiés','MA',''),
    ('3.1.1','3','Déchets d\'écorce et de liège','MA',''),
    ('3.1.2','3','Sciure de bois, copeaux, chutes, bois, panneaux de particules et placages','MA',''),
    ('3.1.99','3','Déchets non spécifiés','MA',''),
    ('3.3.1','3','Déchets d\'écorce et de bois','MA',''),
    ('3.3.2','3','Refus séparés mécaniquement provenant du broyage de déchets de papier et de carton','MA',''),
    ('3.3.3','3','Déchets provenant du tri de papier et de carton destinés au recyclage','MA',''),
    ('3.3.99','3','Déchets non spécifiés','MA',''),
    ('4.2.1','4','Déchets provenant des finitions','MA',''),
    ('4.2.2','4','Fibres textiles non ouvrées','MA',''),
    ('4.2.3','4','Fibres textiles ouvrées','MA',''),
    ('4.2.99','4','Déchets non spécifiés','MA',''),
    ('7.2.1','7','Déchets plastiques','MA',''),
    ('7.2.99','7','Déchets non spécifiés','MA',''),
    ('10.12.1','10','Déchets de préparation avant cuisson','I',''),
    ('10.12.2','10','Moules déclassés','I',''),
    ('10.12.3','10','Déchets de produits en céramique, briques, carrelage et matériaux de construction après cuisson','I',''),
    ('10.12.99','10','Déchets non spécifiés','I',''),
    ('10.13.1','10','Déchets et boues de béton','I',''),
    ('10.13.99','10','Déchets non spécifiés','I',''),
    ('12.1.1','12','Déchets de matières plastiques d\'ébarbage et de tournage','MA',''),
    ('12.1.99','12','Déchets non spécifiés','MA',''),
    ('15.1.1','15','Emballages en papier/carton','MA',''),
    ('15.1.2','15','Emballages en matières plastiques','MA',''),
    ('15.1.3','15','Emballages en bois','MA',''),
    ('15.1.4','15','Emballages métalliques','MA',''),
    ('15.1.5','15','Emballages composites','MA',''),
    ('15.1.6','15','Emballages en mélange','MA',''),
    ('15.1.7','15','Emballages en verre','MA',''),
    ('15.1.8','15','Emballages textiles','MA',''),
    ('15.1.99','15','Déchets non spécifiés','MA',''),
    ('16.1.1','16','Matières plastiques','MA',''),
    ('16.1.2','16','Verre','MA',''),
    ('16.1.99','16','Déchets non spécifiés','MA',''),
    ('17.1.1','17','Béton','I',''),
    ('17.1.2','17','Briques','I',''),
    ('17.1.3','17','Tuiles et céramiques','I',''),
    ('17.1.4','17','Mélanges de béton, brique, tuiles et céramiques','I',''),
    ('17.1.99','17','Déchets non spécifiés','I',''),
    ('17.2.1','17','Bois','MA',''),
    ('17.2.2','17','Verre','MA',''),
    ('17.2.3','17','Matières plastiques','MA',''),
    ('17.2.99','17','Déchets non spécifiés','MA',''),
    ('17.7.1','17','Matériaux de construction à base de gypse','I',''),
    ('17.7.99','17','Déchets non spécifiés','I',''),
    ('17.8.1','17','Déchets de construction et de démolition en mélange','I',''),
    ('17.8.99','17','Déchets non spécifiés','I',''),
    ('19.4.1','19','Déchets vitrifiés','I',''),
    ('19.4.99','19','Déchets non spécifiés','I',''),
    ('19.5.1','19','Fraction non compostée des déchets communaux et assimilés','MA',''),
    ('19.5.2','19','Compost déclassé','MA',''),
    ('19.5.99','19','Déchets non spécifiés','MA',''),
    ('19.12.1','19','Papier et carton','MA',''),
    ('19.12.2','19','Verre','MA',''),
    ('19.12.3','19','Bois','MA',''),
    ('19.12.4','19','Textiles','MA',''),
    ('19.12.5','19','Minéraux (par exemple, sable, cailloux)','I',''),
    ('19.12.99','19','Déchets non spécifiés','MA',''),
    ('20.1.1','20','Papier et carton','MA',''),
    ('20.1.2','20','Verre','MA',''),
    ('20.1.3','20','Déchets de cuisine et de cantine biodégradables','MA',''),
    ('20.1.4','20','Vêtements','MA',''),
    ('20.1.5','20','Textiles','MA',''),
    ('20.1.6','20','Bois','MA',''),
    ('20.1.7','20','Matières plastiques','MA',''),
    ('20.1.99','20','Autres fractions non spécifiées','MA',''),
    ('20.2.1','20','Déchets biodégradables','MA',''),
    ('20.2.2','20','Terres et pierres','I',''),
    ('20.2.3','20','Déchets non biodégradables','MA',''),
    ('20.2.99','20','Déchets non spécifiés','MA',''),
    ('20.3.1','20','Déchets communaux en mélange','MA',''),
    ('20.3.2','20','Déchets de marchés','MA',''),
    ('20.3.3','20','Déchets de nettoyage des rues','MA',''),
    ('20.3.99','20','Déchets communaux non spécifiés','MA',''),
    ('1.1.1','1','Déchets provenant de l\'extraction des minéraux métallifères','S',''),
    ('1.1.2','1','Déchets provenant de l\'extraction des minéraux non métallifères','S',''),
    ('1.1.99','1','Déchets non spécifiés','S',''),
    ('1.2.1','1','Stériles acidogènes provenant de la transformation du sulfure','SD','Comburante, Irritante'),
    ('1.2.2','1','Autres stériles contenant des substances dangereuses','SD','Toxique, Dangereuse pour l\'environnement'),
    ('1.2.3','1','Stériles autres que ceux visés aux rubriques 1.2.1 et 1.2.2','S',''),
    ('1.2.4','1','Autres déchets contenant des substances dangereuses','SD','Toxique, Dangereuse pour l\'environnement'),
    ('1.2.5','1','Déchets de poussières et de poudres','S',''),
    ('1.2.6','1','Boues rouges issues de la production d\'alumine','S',''),
    ('1.2.99','1','Déchets non spécifiés','S',''),
    ('1.3.1x','1','Déchets contenant des substances dangereuses provenant de la transformation des minéraux non métallifères','SD','Toxique, Dangereuse pour l\'environnement'),
    ('1.3.2x','1','Déchets de poussières et de poudres','S',''),
    ('1.3.3x','1','Déchets de la transformation de la potasse et des sels minéraux','S',''),
    ('1.3.4x','1','Stériles et autres déchets provenant du lavage et du nettoyage des minéraux','S',''),
    ('1.3.99x','1','Déchets non spécifiés','S',''),
    ('1.4.1x','1','Boues et autres déchets de forage contenant des hydrocarbures','SD','Inflammable, Toxique'),
    ('1.4.2x','1','Boues et autres déchets de forage contenant des substances dangereuses','SD','Dangereuse pour l\'environnement'),
    ('1.4.3x','1','Boues et autres déchets de forage contenant des sels de baryum','S',''),
    ('1.4.4x','1','Boues et autres déchets de forage contenant des chlorures','S',''),
    ('1.4.99x','1','Déchets non spécifiés','S',''),
    ('2.1.5x','2','Déchets agrochimiques contenant des substances dangereuses','SD','Dangereuse pour l\'environnement'),
    ('2.1.6x','2','Déchets agrochimiques autres que ceux visés à la rubrique 2.1.5','S',''),
    ('3.2.1x','3','Composés organiques non halogénés de protection du bois','SD','Comburante, Inflammable'),
    ('3.2.2x','3','Composés organochlorés de protection du bois','SD','Toxique, Cancérogène, Dangereuse pour l\'environnement'),
    ('3.2.3x','3','Composés organométalliques de protection du bois','SD','Nocive, Dangereuse pour l\'environnement'),
    ('3.2.4x','3','Composés inorganiques de protection du bois','SD','Dangereuse pour l\'environnement'),
    ('3.2.5x','3','Autres produits de protection du bois contenant des substances dangereuses','SD','Dangereuse pour l\'environnement'),
    ('3.2.99x','3','Produits de protection du bois non spécifiés','S',''),
    ('4.1.3x','4','Déchets de dégraissage contenant des solvants sans phase liquide','SD','Inflammable, Toxique'),
    ('4.1.4x','4','Liqueur de tannage contenant du chrome','SD','Toxique'),
    ('4.1.6x','4','Boues provenant du traitement in situ des effluents, contenant du chrome','SD','Toxique'),
    ('4.1.9x','4','Déchets de cuir tanné contenant du chrome','SD','Toxique'),
    ('4.2.3x','4','Déchets provenant des finitions contenant des solvants organiques','SD','Inflammable, Toxique'),
    ('4.2.4x','4','Teintures et pigments contenant des substances dangereuses','SD','Toxique, Dangereuse pour l\'environnement'),
    ('4.2.6x','4','Boues provenant du traitement in situ des effluents contenant des substances dangereuses','SD','Dangereuse pour l\'environnement'),
    ('5.1.1x','5','Boues de dessalage','SD','Irritante'),
    ('5.1.2x','5','Boues de fond de cuves','SD','Dangereuse pour l\'environnement'),
    ('5.1.3x','5','Boues d\'alkyles acides','SD','Facilement inflammable, Toxique, Corrosive'),
    ('5.1.4x','5','Hydrocarbures accidentellement répandus','SD','Toxique, Cancérogène, Mutagène, Dangereuse pour l\'environnement'),
    ('5.1.6x','5','Goudrons acides','SD','Inflammable, Toxique, Cancérogène, Mutagène'),
    ('5.1.7x','5','Autres goudrons et bitumes','SD','Inflammable, Toxique, Cancérogène, Mutagène'),
    ('5.2.1x','5','Goudrons acides','SD','Inflammable, Toxique, Cancérogène, Mutagène'),
    ('5.3.1x','5','Déchets contenant du mercure','SD','Toxique, Toxique vis-à-vis de la reproduction, Dangereuse pour l\'environnement'),
    ('6.1.1x','6','Acide sulfurique et acide sulfureux','SD','Comburante, Inflammable, Toxique, Corrosive, Irritante'),
    ('6.1.2x','6','Acide chlorhydrique','SD','Inflammable, Toxique, Corrosive, Irritante'),
    ('6.1.3x','6','Acide fluorhydrique','SD','Inflammable, Toxique, Corrosive, Irritante'),
    ('6.1.4x','6','Acide phosphorique et acide phosphoreux','SD','Explosive, Toxique'),
    ('6.1.5x','6','Acide nitrique et acide nitreux','SD','Explosive, Toxique'),
    ('6.1.6x','6','Autres acides','SD','Dangereuse pour l\'environnement'),
    ('6.2.1x','6','Hydroxyde de calcium','SD','Nocive'),
    ('6.2.2x','6','Hydroxyde d\'ammonium','SD','Nocive, Comburante'),
    ('6.2.3x','6','Hydroxyde de sodium et hydroxyde de potassium','SD','Explosible'),
    ('6.3.1x','6','Sels solides et solutions contenant des cyanures','SD','Dangereuse pour l\'environnement'),
    ('6.3.2x','6','Sels solides et solutions contenant des métaux lourds','SD','Nocive, Dangereuse pour l\'environnement'),
    ('6.4.1x','6','Déchets contenant de l\'arsenic','SD','Toxique, Toxique vis-à-vis de la reproduction, Dangereuse pour l\'environnement'),
    ('6.4.2x','6','Déchets contenant du mercure','SD','Dangereuse pour l\'environnement'),
    ('6.4.3x','6','Déchets contenant d\'autres métaux lourds','SD','Dangereuse pour l\'environnement'),
    ('6.6.1x','6','Déchets contenant des sulfures dangereux','SD','Inflammable, Toxique'),
    ('6.7.2x','6','Déchets de charbon actif utilisé pour la production du chlore','SD','Toxique, Cancérogène'),
    ('6.7.3x','6','Boues de sulfate de baryum contenant du mercure','SD','Toxique, Toxique vis-à-vis de la reproduction, Dangereuse pour l\'environnement'),
    ('6.9.2x','6','Déchets de réactions basées sur le calcium contenant des substances dangereuses','SD','Corrosive, Irritante'),
    ('6.10.1x','6','Déchets contenant des substances dangereuses','SD','Dangereuse pour l\'environnement'),
    ('6.12.1x','6','Produits phytosanitaires inorganiques, agents de protection du bois et autres biocides','SD','Toxique, Dangereuse pour l\'environnement'),
    ('6.12.4x','6','Déchets provenant de la transformation de l\'amiante','SD','Toxique, Cancérogène'),
    ('7.1.2x','7','Solvants, liquides de lavage et liqueurs mères organiques halogénés','SD','Inflammable, Toxique, Cancérogène'),
    ('7.1.4x','7','Résidus de réaction et résidus de distillation halogénés','SD','Toxique, Cancérogène'),
    ('8.1.1x','8','Déchets de peintures et vernis contenant des solvants organiques ou d\'autres substances dangereuses','SD','Inflammable, Irritante, Toxique, Dangereuse pour l\'environnement'),
    ('9.1.1x','9','Bains de développement aqueux contenant un activateur','SD','Irritante, Nocive'),
    ('9.1.4x','9','Bains de fixation','SD','Nocive'),
    ('9.1.5x','9','Bains de blanchiment et bains de blanchiment/fixation','SD','Irritante, Nocive'),
    ('10.1.4x','10','Cendres volantes et cendres sous chaudière d\'hydrocarbures','SD','Irritante, Toxique'),
    ('10.1.8x','10','Acide sulfurique','SD','Inflammable, Irritante, Toxique, Corrosive'),
    ('13.1.1x','13','Huiles hydrauliques contenant des PCB','SD','Irritante, Toxique, Cancérogène, Dangereuse pour l\'environnement'),
    ('13.2.1x','13','Huile moteur, de boîte de vitesses et de lubrification chlorées à base minérale','SD','Toxique'),
    ('13.3.1x','13','Huiles isolantes et fluides caloporteurs contenant des PCB','SD','Irritante, Toxique, Cancérogène, Dangereuse pour l\'environnement'),
    ('13.6.1x','13','Fuel, oil et diesel','SD','Inflammable, Nocive'),
    ('13.6.2x','13','Essence','SD','Inflammable, Nocive'),
    ('14.1.1x','14','Chlorofluorocarbones, HCFC, HFC','SD','Comburante, Inflammable'),
    ('14.1.2x','14','Autres solvants et mélanges de solvants halogénés','SD','Comburante, Inflammable, Toxique'),
    ('14.1.3x','14','Autres solvants et mélanges de solvants','SD','Toxique vis-à-vis de la reproduction, Inflammable, Toxique'),
    ('15.1.1x','15','Emballages contenant des résidus de substances dangereuses','SD','Dangereuse pour l\'environnement'),
    ('15.2.1x','15','Absorbants, matériaux filtrants, chiffons d\'essuyage et vêtements de protection contaminés par des substances dangereuses','SD','Inflammable, Irritante'),
    ('16.1.4x','16','Filtres à huile','SD','Nocive'),
    ('16.1.5x','16','Composants contenant du mercure','SD','Toxique, Toxique vis-à-vis de la reproduction, Dangereuse pour l\'environnement'),
    ('16.1.6x','16','Composants contenant des PCB','SD','Irritante, Toxique, Cancérogène, Dangereuse pour l\'environnement'),
    ('16.1.7x','16','Composants explosifs (par exemple, coussins gonflables de sécurité)','SD','Explosible, Comburante, Inflammable'),
    ('16.1.8x','16','Patins de freins contenant de l\'amiante','SD','Toxique, Cancérogène'),
    ('16.2.1x','16','Transformateurs et accumulateurs contenant des PCB','SD','Irritante, Toxique, Cancérogène, Dangereuse pour l\'environnement'),
    ('16.4.1x','16','Déchets de munitions','SD','Explosible, Dangereuse pour l\'environnement'),
    ('16.5.1x','16','Gaz en récipients à pression contenant des substances dangereuses','SD','Toxique, Dangereuse pour l\'environnement'),
    ('16.5.3x','16','Produits chimiques de laboratoire contenant des substances dangereuses','SD','Toxique, Dangereuse pour l\'environnement'),
    ('16.6.1x','16','Accumulateurs au plomb','SD','Toxique'),
    ('16.6.2x','16','Accumulateurs Ni-Cd','SD','Toxique'),
    ('16.6.3x','16','Piles contenant du mercure','SD','Toxique, Toxique vis-à-vis de la reproduction, Dangereuse pour l\'environnement'),
    ('16.9.1x','16','Permanganates, par exemple, permanganate de potassium','SD','Toxique'),
    ('16.9.2x','16','Chromates, par exemple, chromate de potassium','SD','Toxique'),
    ('16.9.3x','16','Peroxydes, par exemple, peroxyde d\'hydrogène','SD','Toxique'),
    ('17.3.1x','17','Mélanges bitumineux contenant du goudron','SD','Inflammable, Toxique, Cancérogène, Mutagène'),
    ('17.3.3x','17','Goudron et produits goudronnés','SD','Inflammable, Toxique, Cancérogène, Mutagène'),
    ('17.5.1x','17','Terres et cailloux contenant des substances dangereuses','SD','Dangereuse pour l\'environnement'),
    ('17.5.3x','17','Boues de dragage contenant des substances dangereuses','SD','Dangereuse pour l\'environnement'),
    ('17.6.1x','17','Matériaux d\'isolation contenant de l\'amiante','SD','Toxique, Cancérogène'),
    ('17.6.4x','17','Matériaux de construction contenant de l\'amiante','SD','Dangereuse pour l\'environnement'),
    ('17.8.1x','17','Déchets de construction et de démolition contenant du mercure','SD','Toxique, Toxique vis-à-vis de la reproduction, Dangereuse pour l\'environnement'),
    ('17.8.2x','17','Déchets de construction et de démolition contenant des PCB','SD','Irritante, Toxique, Cancérogène, Dangereuse pour l\'environnement'),
    ('18.1.1x','18','Déchets piquants, coupants et tranchants','SD','Infectieuse'),
    ('18.1.3x','18','Déchets dont la collecte et l\'élimination font l\'objet de prescriptions particulières vis-à-vis des risques d\'infection','SD','Toxique, Infectieuse'),
    ('18.1.5x','18','Produits chimiques à base de ou contenant des substances dangereuses','SD','Toxique'),
    ('18.1.7x','18','Médicaments cytotoxiques et cytostatiques','SD','Toxique, Cancérogène'),
    ('18.1.9x','18','Déchets d\'amalgame dentaire','SD','Toxique, Toxique vis-à-vis de la reproduction, Dangereuse pour l\'environnement'),
    ('19.1.2x','19','Gâteau de filtration provenant de l\'épuration des fumées','SD','Irritante, Toxique'),
    ('19.7.1x','19','Lixiviats des centres d\'enfouissement techniques et des décharges contenant des substances dangereuses','SD','Toxique'),
    ('20.1.1x','20','Solvants','SD','Inflammable, Irritante'),
    ('20.1.2x','20','Acides','SD','Inflammable, Irritante, Toxique'),
    ('20.1.3x','20','Déchets basiques','SD','Irritante, Toxique'),
    ('20.1.5x','20','Pesticides','SD','Toxique, Dangereuse pour l\'environnement'),
    ('20.1.6x','20','Tubes fluorescents et autres déchets contenant du mercure','SD','Toxique, Toxique vis-à-vis de la reproduction, Dangereuse pour l\'environnement'),
    ('20.1.10x','20','Peintures, encres, colles et résines contenant des substances dangereuses','SD','Inflammable, Dangereuse pour l\'environnement'),
    ('20.1.14x','20','Médicaments cytotoxiques et cytostatiques','SD','Toxique, Cancérogène'),
    ('20.1.16x','20','Piles et accumulateurs dangereux','SD','Toxique vis-à-vis de la reproduction, Dangereuse pour l\'environnement'),
    ('20.1.20x','20','Bois contenant des substances dangereuses','SD','Comburante, Dangereuse pour l\'environnement'),
]

# Parse danger string into boolean flags
def parse_dangers(danger_str):
    if not danger_str:
        return {}
    d = danger_str.lower()
    return {
        'explosible': 'explosible' in d or 'explosive' in d,
        'inflammable': 'inflammable' in d or 'facilement inflammable' in d,
        'toxique': 'toxique' in d,
        'cancerogene': 'cancérogène' in d,
        'corrosive': 'corrosive' in d or 'corrosif' in d,
        'infectieuse': 'infectieuse' in d or 'infectieux' in d or 'infecti' in d,
        'dangereuse_environnement': 'environnement' in d,
    }

created = 0
updated = 0
for code_raw, famille, nom_fr, classe, danger_fr in DATA:
    # Normalize code: strip trailing 'x' from duplicate codes and zero-pad
    code_clean = code_raw.rstrip('x')
    parts = code_clean.split('.')
    code = f"{int(parts[0]):02d}.{int(parts[1]):02d}.{int(parts[2]):02d}"

    # Avoid duplicate codes — skip if already exists
    if Nomenclature.objects.filter(code=code).exists():
        continue

    dangers = parse_dangers(danger_fr)
    sous_famille = f"{int(parts[0]):02d}.{int(parts[1]):02d}"

    obj, was_created = Nomenclature.objects.update_or_create(
        code=code,
        defaults={
            'famille': famille,
            'sous_famille': sous_famille,
            'designation_fr': nom_fr,
            'designation_ar': '',
            'classe': classe,
            'dangerosite_fr': danger_fr,
            'dangerosite_ar': '',
            'bsd_obligatoire': (classe == 'SD'),
            'agrement_requis': (classe == 'SD'),
            **dangers,
        }
    )
    if was_created:
        created += 1
    else:
        updated += 1

total = Nomenclature.objects.count()
print(f'✅ Seed frontend nomenclature: {created} créés, {updated} mis à jour')
print(f'   Total en base : {total} codes')
