# Generated by Django 6.0.6 on 2026-06-23 13:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contexte', models.CharField(choices=[('GENERAL', 'Général'), ('AGREMENTS', 'Agréments'), ('BSD', 'Bordereaux de suivi des déchets'), ('NOMENCLATURE', 'Nomenclature des déchets'), ('STOCKS', 'Stocks et opérations'), ('REGLEMENTAIRE', 'Réglementaire'), ('DASHBOARD', 'Tableau de bord')], default='GENERAL', max_length=30)),
                ('entite_id', models.CharField(blank=True, max_length=50)),
                ('titre', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('USER', 'Utilisateur'), ('ASSISTANT', 'Assistant IA'), ('SYSTEM', 'Système')], default='USER', max_length=20)),
                ('message', models.TextField()),
                ('contexte_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_assistant.aiconversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_recommandation', models.CharField(choices=[('GENERAL', 'Générale'), ('AGREMENT', 'Agrément'), ('BSD', 'BSD'), ('NOMENCLATURE', 'Nomenclature'), ('STOCK', 'Stock'), ('DECLARATION', 'Déclaration'), ('REGLEMENTAIRE', 'Réglementaire')], default='GENERAL', max_length=30)),
                ('recommandation', models.TextField()),
                ('contexte_json', models.JSONField(blank=True, default=dict)),
                ('statut', models.CharField(choices=[('ACTIVE', 'Active'), ('EN_ATTENTE', 'En attente'), ('REJETEE', 'Rejetée'), ('REALISEE', 'Réalisée'), ('EXPIREE', 'Expirée')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_echeance', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('LOI', 'Loi'), ('DECRET', 'Décret'), ('REFERENTIEL', 'Référentiel'), ('GLOSSAIRE', 'Glossaire'), ('FAQ', 'FAQ'), ('GUIDE', 'Guide'), ('PROCEDURE', 'Procédure'), ('DECHETS_HOSPITALIERS', 'Déchets hospitaliers'), ('DECLARATION_TRIMESTRIELLE', 'Déclarations trimestrielles'), ('AUTRE', 'Autre')], default='AUTRE', max_length=40)),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('reference_reglementaire', models.CharField(blank=True, max_length=200)),
                ('langue', models.CharField(default='fr', max_length=5)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('date_mise_a_jour', models.DateField(default=django.utils.timezone.now)),
                ('est_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['categorie', 'titre'],
                'indexes': [models.Index(fields=['categorie', 'est_active'], name='ai_assistan_categor_c26e1c_idx'), models.Index(fields=['reference_reglementaire'], name='ai_assistan_referen_176531_idx'), models.Index(fields=['langue', 'est_active'], name='ai_assistan_langue_aa13b4_idx')],
            },
        ),
        migrations.CreateModel(
            name='AIAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_alerte', models.CharField(choices=[('AGREMENT_EXPIRE', 'Agrément expiré'), ('AGREMENT_EXPIRING', 'Agrément bientôt expiré'), ('AGREMENT_STATUT', 'Statut agrément inhabituel'), ('BSD_ANOMALIE', 'Anomalie BSD'), ('BSD_SIGNATURE_MANQUANTE', 'Signature BSD manquante'), ('BSD_CODE_INCONNU', 'Code déchet BSD inconnu'), ('DECLARATION_RETARD', 'Déclaration en retard'), ('STOCK_ELEVE', 'Stock élevé'), ('REGLEMENTAIRE', 'Information réglementaire'), ('INFO', 'Information')], default='INFO', max_length=30)),
                ('niveau', models.CharField(choices=[('INFO', 'Information'), ('FAIBLE', 'Faible'), ('MOYEN', 'Moyen'), ('ELEVE', 'Élevé'), ('CRITIQUE', 'Critique')], default='MOYEN', max_length=15)),
                ('description', models.TextField()),
                ('entite_type', models.CharField(blank=True, max_length=50)),
                ('entite_id', models.CharField(blank=True, max_length=50)),
                ('lien', models.CharField(blank=True, max_length=500)),
                ('est_lue', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'est_lue', 'created_at'], name='ai_assistan_user_id_229344_idx'), models.Index(fields=['type_alerte', 'created_at'], name='ai_assistan_type_al_441846_idx'), models.Index(fields=['entite_type', 'entite_id'], name='ai_assistan_entite__06e7a2_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='aiconversation',
            index=models.Index(fields=['user', 'created_at'], name='ai_assistan_user_id_9e4e24_idx'),
        ),
        migrations.AddIndex(
            model_name='aiconversation',
            index=models.Index(fields=['contexte', 'created_at'], name='ai_assistan_context_be2616_idx'),
        ),
        migrations.AddIndex(
            model_name='aiconversation',
            index=models.Index(fields=['entite_id', 'contexte'], name='ai_assistan_entite__57124d_idx'),
        ),
        migrations.AddIndex(
            model_name='aimessage',
            index=models.Index(fields=['conversation', 'created_at'], name='ai_assistan_convers_8fde2e_idx'),
        ),
        migrations.AddIndex(
            model_name='aimessage',
            index=models.Index(fields=['role', 'created_at'], name='ai_assistan_role_b4200c_idx'),
        ),
        migrations.AddIndex(
            model_name='airecommendation',
            index=models.Index(fields=['user', 'statut', 'created_at'], name='ai_assistan_user_id_780dbd_idx'),
        ),
        migrations.AddIndex(
            model_name='airecommendation',
            index=models.Index(fields=['type_recommandation', 'statut'], name='ai_assistan_type_re_0589fb_idx'),
        ),
    ]
