// Glossaire de la terminologie des déchets — Français / العربية
// Conforme à la Loi n°01-19 et au Décret exécutif n°06-104
 
export const CATEGORIES = [
  { id: 'general',       label_fr: 'Termes généraux',                    label_ar: 'المصطلحات العامة'               },
  { id: 'types',         label_fr: 'Types de déchets',                   label_ar: 'أنواع النفايات'                 },
  { id: 'acteurs',       label_fr: 'Acteurs et opérateurs',              label_ar: 'الفاعلون والمشغلون'             },
  { id: 'documents',     label_fr: 'Documents réglementaires',           label_ar: 'الوثائق التنظيمية'              },
  { id: 'operations',    label_fr: 'Opérations de gestion',              label_ar: 'عمليات التسيير'                 },
  { id: 'danger',        label_fr: 'Dangerosité et critères',            label_ar: 'الخطورة والمعايير'              },
  { id: 'juridique',     label_fr: 'Cadre juridique',                    label_ar: 'الإطار القانوني'                },
  { id: 'installations', label_fr: 'Installations et infrastructures',   label_ar: 'المنشآت والبنية التحتية'       },
]
 
export const GLOSSAIRE = [
  // ── TERMES GÉNÉRAUX ───────────────────────────────────────────────────────
  {
    id: 1, categorie: 'general',
    terme_fr: 'Déchet',
    terme_ar: 'نفاية',
    definition_fr: 'Tout résidu d\'un processus de production, de transformation ou d\'utilisation, toute substance, matériau, produit ou, plus généralement, tout bien meuble abandonné ou que son détenteur destine à l\'abandon.',
    definition_ar: 'كل بقايا عملية إنتاج أو تحويل أو استخدام، وكل مادة أو منتج أو بصفة أعم كل منقول مُهجَر أو يعتزم حائزه التخلي عنه.',
    reference: 'Loi n°01-19, Art. 3',
    classe: null,
  },
  {
    id: 2, categorie: 'general',
    terme_fr: 'Gestion des déchets',
    terme_ar: 'تسيير النفايات',
    definition_fr: 'La collecte, le tri, le transport, le stockage, la valorisation et l\'élimination des déchets, y compris le contrôle de ces opérations ainsi que la surveillance des sites de décharge après leur fermeture.',
    definition_ar: 'جمع النفايات وفرزها ونقلها وتخزينها وتثمينها وإزالتها، بما في ذلك مراقبة هذه العمليات ومتابعة مواقع الطمر بعد غلقها.',
    reference: 'Loi n°01-19, Art. 3',
    classe: null,
  },
  {
    id: 3, categorie: 'general',
    terme_fr: 'Producteur de déchets',
    terme_ar: 'منتج النفايات',
    definition_fr: 'Toute personne physique ou morale dont l\'activité produit des déchets (producteur initial) ou toute personne qui effectue des opérations de traitement, de mélange ou autres qui entraînent un changement de nature ou de composition de ces déchets.',
    definition_ar: 'كل شخص طبيعي أو معنوي تنتج عن نشاطه نفايات (المنتج الأولي) أو كل شخص يقوم بعمليات معالجة أو خلط أو غيرها تؤدي إلى تغيير طبيعة هذه النفايات أو تركيبها.',
    reference: 'Loi n°01-19, Art. 3',
    classe: null,
  },
  {
    id: 4, categorie: 'general',
    terme_fr: 'Détenteur de déchets',
    terme_ar: 'حائز النفايات',
    definition_fr: 'Le producteur des déchets ou la personne physique ou morale qui a des déchets en sa possession.',
    definition_ar: 'منتج النفايات أو الشخص الطبيعي أو المعنوي الذي بحوزته نفايات.',
    reference: 'Loi n°01-19, Art. 3',
    classe: null,
  },
  {
    id: 5, categorie: 'general',
    terme_fr: 'Récupération',
    terme_ar: 'استرداد',
    definition_fr: 'Opération de collecte et de tri des déchets en vue de les réutiliser, de les recycler ou de les valoriser.',
    definition_ar: 'عملية جمع النفايات وفرزها بهدف إعادة استخدامها أو تدويرها أو تثمينها.',
    reference: 'Décret n°06-104',
    classe: null,
  },
  {
    id: 6, categorie: 'general',
    terme_fr: 'Traçabilité',
    terme_ar: 'تتبع المسار',
    definition_fr: 'Aptitude à retrouver l\'historique, la mise en œuvre ou l\'emplacement de tout ce qui est sous examen. Pour les déchets : suivi du déchet de sa production jusqu\'à son élimination finale.',
    definition_ar: 'القدرة على استرجاع تاريخ وتطبيق وموقع كل ما هو قيد الفحص. بالنسبة للنفايات: متابعة النفاية من إنتاجها إلى إزالتها النهائية.',
    reference: 'Loi n°01-19',
    classe: null,
  },
 
  // ── TYPES DE DÉCHETS ─────────────────────────────────────────────────────
  {
    id: 7, categorie: 'types',
    terme_fr: 'Déchets ménagers et assimilés (MA)',
    terme_ar: 'النفايات المنزلية والمماثلة',
    definition_fr: 'Déchets issus des activités des ménages ainsi que les déchets similaires par leur nature et leur composition provenant des activités industrielles, commerciales, artisanales et de service.',
    definition_ar: 'النفايات الناجمة عن نشاطات الأسر المعيشية والنفايات المماثلة في طبيعتها وتركيبها الصادرة عن النشاطات الصناعية والتجارية والحرفية وقطاع الخدمات.',
    reference: 'Loi n°01-19, Art. 4',
    classe: 'MA',
  },
  {
    id: 8, categorie: 'types',
    terme_fr: 'Déchets inertes (I)',
    terme_ar: 'النفايات الخاملة',
    definition_fr: 'Déchets qui ne subissent aucune modification physique, chimique ou biologique importante. Ils ne se dissolvent pas, ne brûlent pas et ne produisent aucune réaction physique ou chimique.',
    definition_ar: 'نفايات لا تخضع لأي تحول فيزيائي أو كيميائي أو بيولوجي مهم. لا تذوب ولا تحترق ولا تنتج أي تفاعل فيزيائي أو كيميائي.',
    reference: 'Décret n°06-104',
    classe: 'I',
  },
  {
    id: 9, categorie: 'types',
    terme_fr: 'Déchets spéciaux (S)',
    terme_ar: 'النفايات الخاصة',
    definition_fr: 'Déchets issus des activités industrielles, agricoles, de soins et d\'une manière générale de toute activité économique, qui en raison de leur nature et de la composition des substances qu\'ils contiennent, ne peuvent être collectés, transportés ou traités dans les mêmes conditions que les déchets ménagers.',
    definition_ar: 'نفايات ناجمة عن النشاطات الصناعية والفلاحية وأعمال العلاج وبصفة عامة عن أي نشاط اقتصادي، التي بسبب طبيعتها وتركيب المواد التي تحتوي عليها لا يمكن جمعها ونقلها أو معالجتها في نفس شروط النفايات المنزلية.',
    reference: 'Loi n°01-19, Art. 4',
    classe: 'S',
  },
  {
    id: 10, categorie: 'types',
    terme_fr: 'Déchets spéciaux dangereux (SD)',
    terme_ar: 'النفايات الخاصة الخطرة',
    definition_fr: 'Déchets spéciaux qui, en raison de leurs propriétés physiques, chimiques, biologiques ou radioactives, présentent des risques particuliers pour l\'homme et l\'environnement et nécessitent, de ce fait, un traitement spécifique.',
    definition_ar: 'نفايات خاصة تشكل، بسبب خصائصها الفيزيائية أو الكيميائية أو البيولوجية أو الإشعاعية، مخاطر خاصة للإنسان والبيئة وتستلزم لذلك معالجة خاصة.',
    reference: 'Loi n°01-19, Art. 4',
    classe: 'SD',
  },
  {
    id: 11, categorie: 'types',
    terme_fr: 'Déchets d\'activités de soins',
    terme_ar: 'نفايات نشاطات العلاج',
    definition_fr: 'Déchets issus des activités de diagnostic, de suivi et de traitement préventif, curatif ou palliatif, dans les domaines de la médecine humaine et vétérinaire.',
    definition_ar: 'نفايات ناجمة عن نشاطات التشخيص والمتابعة والعلاج الوقائي أو العلاجي أو التلطيفي في مجالي الطب البشري والبيطري.',
    reference: 'Loi n°01-19',
    classe: 'S',
  },
  {
    id: 12, categorie: 'types',
    terme_fr: 'Déchets d\'emballage',
    terme_ar: 'نفايات التغليف',
    definition_fr: 'Tout emballage ou matériau d\'emballage dont le détenteur se défait ou a l\'intention ou l\'obligation de se défaire, à l\'exclusion des résidus de production.',
    definition_ar: 'كل تغليف أو مادة تغليف يتخلص منها الحائز أو ينوي أو يلزم التخلص منها، باستثناء بقايا الإنتاج.',
    reference: 'Décret n°06-104',
    classe: 'MA',
  },
 
  // ── ACTEURS ───────────────────────────────────────────────────────────────
  {
    id: 13, categorie: 'acteurs',
    terme_fr: 'Récupérateur',
    terme_ar: 'المسترد',
    definition_fr: 'Personne physique ou morale agréée qui exerce l\'activité de collecte et de tri des déchets en vue de leur réutilisation, recyclage ou valorisation. Il existe 3 catégories selon le type de déchets traités et la possession ou non d\'un agrément.',
    definition_ar: 'شخص طبيعي أو معنوي معتمد يمارس نشاط جمع وفرز النفايات بهدف إعادة استخدامها أو تدويرها أو تثمينها. يوجد 3 أصناف حسب نوع النفايات المعالجة وامتلاك اعتماد أم لا.',
    reference: 'Décret n°06-104',
    classe: null,
  },
  {
    id: 14, categorie: 'acteurs',
    terme_fr: 'Transporteur de déchets',
    terme_ar: 'ناقل النفايات',
    definition_fr: 'Personne physique ou morale qui prend en charge le transport des déchets de leur lieu de production ou de collecte jusqu\'aux installations de traitement ou d\'élimination.',
    definition_ar: 'شخص طبيعي أو معنوي يتولى نقل النفايات من مكان إنتاجها أو جمعها إلى منشآت المعالجة أو الإزالة.',
    reference: 'Loi n°01-19',
    classe: null,
  },
  {
    id: 15, categorie: 'acteurs',
    terme_fr: 'Éliminateur',
    terme_ar: 'المزيل',
    definition_fr: 'Personne physique ou morale qui assure, à titre professionnel, l\'élimination des déchets par incinération, enfouissement technique ou tout autre procédé autorisé.',
    definition_ar: 'شخص طبيعي أو معنوي يضمن، بصفة مهنية، إزالة النفايات عن طريق الحرق أو الطمر التقني أو أي إجراء مرخص آخر.',
    reference: 'Loi n°01-19',
    classe: null,
  },
  {
    id: 16, categorie: 'acteurs',
    terme_fr: 'Valorisateur',
    terme_ar: 'المثمِّن',
    definition_fr: 'Personne physique ou morale qui réalise des opérations de valorisation des déchets, notamment le recyclage, la régénération, le compostage ou la récupération d\'énergie.',
    definition_ar: 'شخص طبيعي أو معنوي يقوم بعمليات تثمين النفايات، ولا سيما التدوير والتجديد وصنع السماد أو استرداد الطاقة.',
    reference: 'Loi n°01-19',
    classe: null,
  },
  {
    id: 17, categorie: 'acteurs',
    terme_fr: 'Acheteur de déchets',
    terme_ar: 'مشتري النفايات',
    definition_fr: 'Personne physique ou morale qui achète des déchets triés ou valorisés en vue de leur utilisation comme matières premières secondaires dans un processus de production.',
    definition_ar: 'شخص طبيعي أو معنوي يشتري نفايات مفرزة أو مثمَّنة بهدف استخدامها كمواد خام ثانوية في عملية إنتاج.',
    reference: 'Décret n°06-104',
    classe: null,
  },
  {
    id: 18, categorie: 'acteurs',
    terme_fr: 'Centre d\'Enfouissement Technique (CET)',
    terme_ar: 'مركز الردم التقني',
    definition_fr: 'Installation destinée au stockage définitif souterrain des déchets non dangereux, conçue et exploitée selon des normes techniques strictes pour éviter toute pollution du sol et des eaux souterraines.',
    definition_ar: 'منشأة مخصصة للتخزين النهائي تحت الأرض للنفايات غير الخطرة، مصممة ومستغلة وفق معايير تقنية صارمة لتفادي أي تلوث للتربة والمياه الجوفية.',
    reference: 'Loi n°01-19',
    classe: null,
  },
 
  // ── DOCUMENTS RÉGLEMENTAIRES ─────────────────────────────────────────────
  {
    id: 19, categorie: 'documents',
    terme_fr: 'Bordereau de Suivi des Déchets (BSD)',
    terme_ar: 'بوليصة متابعة النفايات',
    definition_fr: 'Document administratif qui accompagne les déchets spéciaux dangereux lors de leur transport. Il permet le suivi des déchets depuis leur production jusqu\'à leur élimination finale et garantit la traçabilité.',
    definition_ar: 'وثيقة إدارية ترافق النفايات الخاصة الخطرة أثناء نقلها. تتيح متابعة النفايات من إنتاجها إلى إزالتها النهائية وتضمن تتبع المسار.',
    reference: 'Décret n°05-315',
    classe: null,
  },
  {
    id: 20, categorie: 'documents',
    terme_fr: 'Agrément',
    terme_ar: 'الاعتماد',
    definition_fr: 'Autorisation administrative délivrée par l\'autorité compétente (Direction de wilaya ou Ministère) permettant à un opérateur d\'exercer légalement une activité de gestion des déchets spéciaux ou dangereux.',
    definition_ar: 'ترخيص إداري تمنحه السلطة المختصة (مديرية الولاية أو الوزارة) يخول المشغل ممارسة نشاط تسيير النفايات الخاصة أو الخطرة بصفة قانونية.',
    reference: 'Décret n°06-104',
    classe: null,
  },
  {
    id: 21, categorie: 'documents',
    terme_fr: 'Déclaration des déchets spéciaux dangereux (DSD)',
    terme_ar: 'تصريح بالنفايات الخاصة الخطرة',
    definition_fr: 'Déclaration annuelle obligatoire que tout producteur de déchets spéciaux dangereux doit transmettre à l\'administration chargée de l\'environnement dans les 3 mois suivant la clôture de l\'année.',
    definition_ar: 'تصريح سنوي إلزامي يجب على كل منتج للنفايات الخاصة الخطرة إرساله إلى الإدارة المكلفة بالبيئة في أجل 3 أشهر بعد إقفال السنة.',
    reference: 'Décret n°05-315',
    classe: null,
  },
  {
    id: 22, categorie: 'documents',
    terme_fr: 'Plan de gestion des déchets',
    terme_ar: 'مخطط تسيير النفايات',
    definition_fr: 'Document de planification établi par les autorités compétentes définissant les objectifs et les moyens de gestion des déchets sur un territoire donné.',
    definition_ar: 'وثيقة تخطيطية تضعها السلطات المختصة تحدد أهداف وسائل تسيير النفايات في إقليم معين.',
    reference: 'Loi n°01-19',
    classe: null,
  },
  {
    id: 23, categorie: 'documents',
    terme_fr: 'Registre des déchets',
    terme_ar: 'سجل النفايات',
    definition_fr: 'Document tenu par tout producteur ou détenteur de déchets répertoriant la nature, la quantité, la destination et les modalités de traitement des déchets produits.',
    definition_ar: 'وثيقة يمسكها كل منتج أو حائز للنفايات تجمع طبيعة وكمية ووجهة وكيفيات معالجة النفايات المنتجة.',
    reference: 'Loi n°01-19',
    classe: null,
  },
 
  // ── OPÉRATIONS ────────────────────────────────────────────────────────────
  {
    id: 24, categorie: 'operations',
    terme_fr: 'Collecte',
    terme_ar: 'الجمع',
    definition_fr: 'Opération de ramassage des déchets en vue de leur acheminement vers des installations de traitement, de valorisation ou d\'élimination.',
    definition_ar: 'عملية جمع النفايات بهدف توجيهها نحو منشآت المعالجة أو التثمين أو الإزالة.',
    reference: 'Loi n°01-19',
    classe: null,
  },
  {
    id: 25, categorie: 'operations',
    terme_fr: 'Tri',
    terme_ar: 'الفرز',
    definition_fr: 'Opération consistant à séparer les différents types de déchets afin de faciliter leur traitement, leur valorisation ou leur élimination.',
    definition_ar: 'عملية تقوم على فصل أنواع النفايات المختلفة بهدف تسهيل معالجتها أو تثمينها أو إزالتها.',
    reference: 'Loi n°01-19',
    classe: null,
  },
  {
    id: 26, categorie: 'operations',
    terme_fr: 'Valorisation',
    terme_ar: 'التثمين',
    definition_fr: 'Toute opération dont le résultat principal est que des déchets servent à des fins utiles en remplaçant d\'autres matières qui auraient été utilisées à une fin particulière. Elle comprend le recyclage, la réutilisation, le compostage et la valorisation énergétique.',
    definition_ar: 'كل عملية تكون نتيجتها الرئيسية أن تُستخدم النفايات لأغراض مفيدة بدلاً من مواد أخرى كان يمكن استخدامها لغرض معين. وتشمل التدوير وإعادة الاستخدام وصنع السماد والتثمين الطاقوي.',
    reference: 'Loi n°01-19, Art. 3',
    classe: null,
  },
  {
    id: 27, categorie: 'operations',
    terme_fr: 'Recyclage',
    terme_ar: 'إعادة التدوير',
    definition_fr: 'Toute opération de valorisation par laquelle les déchets sont retraités en substances, matières ou produits aux fins de leur fonction initiale ou à d\'autres fins.',
    definition_ar: 'كل عملية تثمين تُعاد فيها معالجة النفايات في مواد أو أغراض لوظيفتها الأصلية أو لأغراض أخرى.',
    reference: 'Loi n°01-19',
    classe: null,
  },
  {
    id: 28, categorie: 'operations',
    terme_fr: 'Réutilisation',
    terme_ar: 'إعادة الاستخدام',
    definition_fr: 'Toute opération par laquelle des produits ou des composants qui ne sont pas des déchets sont utilisés de nouveau pour un usage identique à celui pour lequel ils avaient été conçus.',
    definition_ar: 'كل عملية تُستخدم فيها منتجات أو مكونات ليست نفايات من جديد للغرض ذاته الذي صُمِّمت من أجله.',
    reference: 'Loi n°01-19',
    classe: null,
  },
  {
    id: 29, categorie: 'operations',
    terme_fr: 'Élimination',
    terme_ar: 'الإزالة',
    definition_fr: 'Toute opération qui n\'est pas de la valorisation même lorsque ladite opération a comme conséquence secondaire la récupération de substances ou d\'énergie. Comprend l\'enfouissement, l\'incinération sans récupération d\'énergie.',
    definition_ar: 'كل عملية لا تُعدّ تثميناً حتى ولو كانت لتلك العملية نتيجة ثانوية هي استرداد مواد أو طاقة. تشمل الطمر والحرق دون استرداد الطاقة.',
    reference: 'Loi n°01-19',
    classe: null,
  },
  {
    id: 30, categorie: 'operations',
    terme_fr: 'Compostage',
    terme_ar: 'صنع السماد',
    definition_fr: 'Procédé de traitement biologique aérobie des matières organiques contenues dans les déchets, permettant d\'obtenir un produit stabilisé utilisable comme amendement organique des sols.',
    definition_ar: 'إجراء معالجة بيولوجية هوائية للمواد العضوية الموجودة في النفايات، يتيح الحصول على منتج مستقر يمكن استخدامه كسماد عضوي للتربة.',
    reference: 'Décret n°06-104',
    classe: null,
  },
  {
    id: 31, categorie: 'operations',
    terme_fr: 'Stockage',
    terme_ar: 'التخزين',
    definition_fr: 'Dépôt temporaire de déchets dans des installations où ils sont gardés en attendant leur collecte, tri, traitement, valorisation ou élimination dans un délai défini.',
    definition_ar: 'إيداع مؤقت للنفايات في منشآت تُحفظ فيها في انتظار جمعها أو فرزها أو معالجتها أو تثمينها أو إزالتها في أجل محدد.',
    reference: 'Loi n°01-19',
    classe: null,
  },
  {
    id: 32, categorie: 'operations',
    terme_fr: 'Incinération',
    terme_ar: 'الحرق',
    definition_fr: 'Procédé thermique de traitement des déchets par combustion à haute température dans des installations spécialement conçues (incinérateurs), permettant la réduction du volume des déchets.',
    definition_ar: 'إجراء حراري لمعالجة النفايات بالاحتراق في درجات حرارة عالية في منشآت مصممة خصيصاً (محارق)، يتيح تقليص حجم النفايات.',
    reference: 'Loi n°01-19',
    classe: null,
  },
 
  // ── DANGEROSITÉ ───────────────────────────────────────────────────────────
  {
    id: 33, categorie: 'danger',
    terme_fr: 'Déchet explosible',
    terme_ar: 'نفاية قابلة للانفجار',
    definition_fr: 'Déchet pouvant exploser sous l\'effet d\'une flamme ou qui est plus sensible aux chocs ou aux frottements que le dinitrobenzène.',
    definition_ar: 'نفاية يمكنها الانفجار تحت تأثير لهب أو أكثر حساسية للصدمات أو الاحتكاك من ثنائي نيتروبنزين.',
    reference: 'Décret n°05-315, Annexe',
    classe: 'SD',
  },
  {
    id: 34, categorie: 'danger',
    terme_fr: 'Déchet inflammable',
    terme_ar: 'نفاية قابلة للاشتعال',
    definition_fr: 'Déchet liquide dont le point d\'éclair est inférieur à 21°C, ou déchet qui peut s\'enflammer spontanément à l\'air à température ambiante.',
    definition_ar: 'نفاية سائلة نقطة اشتعالها أقل من 21 درجة مئوية، أو نفاية يمكنها الاشتعال تلقائياً في الهواء عند درجة حرارة الغرفة.',
    reference: 'Décret n°05-315, Annexe',
    classe: 'SD',
  },
  {
    id: 35, categorie: 'danger',
    terme_fr: 'Déchet toxique',
    terme_ar: 'نفاية سامة',
    definition_fr: 'Déchet pouvant entraîner des risques aigus ou chroniques de mort ou de lésions graves de la santé humaine lorsqu\'il est ingéré, inhalé ou absorbé par la peau.',
    definition_ar: 'نفاية يمكنها إحداث مخاطر حادة أو مزمنة بالوفاة أو إصابات خطيرة للصحة البشرية عند ابتلاعها أو استنشاقها أو امتصاصها عبر الجلد.',
    reference: 'Décret n°05-315, Annexe',
    classe: 'SD',
  },
  {
    id: 36, categorie: 'danger',
    terme_fr: 'Déchet corrosif',
    terme_ar: 'نفاية آكلة',
    definition_fr: 'Déchet pouvant détruire les tissus vivants au contact ou pouvant attaquer d\'autres matières (métaux notamment).',
    definition_ar: 'نفاية يمكنها تدمير الأنسجة الحية عند الاتصال أو يمكنها مهاجمة مواد أخرى (المعادن خاصة).',
    reference: 'Décret n°05-315, Annexe',
    classe: 'SD',
  },
  {
    id: 37, categorie: 'danger',
    terme_fr: 'Déchet infectieux',
    terme_ar: 'نفاية معدية',
    definition_fr: 'Déchet contenant des micro-organismes viables ou leurs toxines, dont on sait ou dont on a de bonnes raisons de croire qu\'ils causent des maladies chez l\'homme ou chez d\'autres organismes vivants.',
    definition_ar: 'نفاية تحتوي على كائنات دقيقة حية أو سمومها، يُعلم أو توجد أسباب وجيهة للاعتقاد بأنها تسبب أمراضاً لدى الإنسان أو الكائنات الحية الأخرى.',
    reference: 'Décret n°05-315, Annexe',
    classe: 'SD',
  },
  {
    id: 38, categorie: 'danger',
    terme_fr: 'Déchet cancérogène',
    terme_ar: 'نفاية مسرطنة',
    definition_fr: 'Déchet susceptible de provoquer un cancer ou d\'en augmenter la fréquence par inhalation, ingestion ou pénétration cutanée.',
    definition_ar: 'نفاية قد تسبب السرطان أو تزيد من تواتره عن طريق الاستنشاق أو الابتلاع أو التخلل الجلدي.',
    reference: 'Décret n°05-315, Annexe',
    classe: 'SD',
  },
 
  // ── CADRE JURIDIQUE ───────────────────────────────────────────────────────
  {
    id: 39, categorie: 'juridique',
    terme_fr: 'Loi n°01-19',
    terme_ar: 'القانون رقم 01-19',
    definition_fr: 'Loi du 12 décembre 2001 relative à la gestion, au contrôle et à l\'élimination des déchets. Texte fondamental du droit algérien des déchets fixant les principes généraux, les responsabilités et les obligations de chaque acteur.',
    definition_ar: 'قانون 12 ديسمبر 2001 المتعلق بتسيير النفايات ومراقبتها وإزالتها. النص الأساسي للقانون الجزائري للنفايات الذي يحدد المبادئ العامة والمسؤوليات والالتزامات لكل فاعل.',
    reference: 'J.O. n°77 du 15/12/2001',
    classe: null,
  },
  {
    id: 40, categorie: 'juridique',
    terme_fr: 'Décret exécutif n°06-104',
    terme_ar: 'المرسوم التنفيذي رقم 06-104',
    definition_fr: 'Décret du 28 février 2006 fixant la nomenclature des déchets, y compris les déchets spéciaux dangereux. Il établit la liste officielle des 208 codes de déchets classés en 4 catégories (MA, I, S, SD).',
    definition_ar: 'مرسوم 28 فبراير 2006 الذي يحدد تسمية النفايات بما فيها النفايات الخاصة الخطرة. يضع القائمة الرسمية لـ208 رمزاً للنفايات مصنفة في 4 فئات (MA ،I ،S ،SD).',
    reference: 'J.O. n°15 du 05/03/2006',
    classe: null,
  },
  {
    id: 41, categorie: 'juridique',
    terme_fr: 'Décret exécutif n°05-315',
    terme_ar: 'المرسوم التنفيذي رقم 05-315',
    definition_fr: 'Décret du 10 septembre 2005 fixant les modalités de déclaration des déchets spéciaux dangereux. Il impose la déclaration annuelle obligatoire et définit le formulaire officiel (BSD).',
    definition_ar: 'مرسوم 10 سبتمبر 2005 الذي يحدد كيفيات التصريح بالنفايات الخاصة الخطرة. يفرض التصريح السنوي الإلزامي ويحدد الاستمارة الرسمية (BSD).',
    reference: 'J.O. n°62 du 11/09/2005',
    classe: null,
  },
  {
    id: 42, categorie: 'juridique',
    terme_fr: 'Principe pollueur-payeur',
    terme_ar: 'مبدأ الملوِّث الدافع',
    definition_fr: 'Principe selon lequel les frais résultant des mesures de prévention, de réduction de la pollution et de lutte contre celle-ci doivent être supportés par le pollueur.',
    definition_ar: 'مبدأ مفاده أن تكاليف تدابير منع التلوث والحد منه ومكافحته يجب أن يتحملها الملوِّث.',
    reference: 'Loi n°01-19, Art. 2',
    classe: null,
  },
  {
    id: 43, categorie: 'juridique',
    terme_fr: 'Responsabilité élargie du producteur',
    terme_ar: 'المسؤولية الموسعة للمنتج',
    definition_fr: 'Principe selon lequel la responsabilité du producteur d\'un produit est étendue à l\'étape post-consommation du cycle de vie du produit, notamment pour la collecte, le tri, le traitement et la valorisation.',
    definition_ar: 'مبدأ تُوسَّع بموجبه مسؤولية منتج المنتج لتشمل مرحلة ما بعد الاستهلاك في دورة حياة المنتج، ولا سيما للجمع والفرز والمعالجة والتثمين.',
    reference: 'Loi n°01-19',
    classe: null,
  },
 
  // ── INSTALLATIONS ─────────────────────────────────────────────────────────
  {
    id: 44, categorie: 'installations',
    terme_fr: 'Décharge',
    terme_ar: 'مطرح النفايات',
    definition_fr: 'Lieu où sont déposés, stockés ou éliminés les déchets, à l\'exclusion des installations de stockage en interne chez le producteur et des installations de transfert.',
    definition_ar: 'مكان تُودَع فيه النفايات أو تُخزَّن أو تُزال، باستثناء منشآت التخزين الداخلي لدى المنتج ومنشآت النقل.',
    reference: 'Loi n°01-19',
    classe: null,
  },
  {
    id: 45, categorie: 'installations',
    terme_fr: 'Déchetterie',
    terme_ar: 'نقطة الاسترداد',
    definition_fr: 'Installation permettant aux particuliers et aux professionnels de déposer leurs déchets triés par catégorie pour leur recyclage ou leur valorisation.',
    definition_ar: 'منشأة تتيح للأفراد والمهنيين إيداع نفاياتهم مفرزة حسب الفئة لتدويرها أو تثمينها.',
    reference: 'Loi n°01-19',
    classe: null,
  },
  {
    id: 46, categorie: 'installations',
    terme_fr: 'Station de transfert',
    terme_ar: 'محطة النقل',
    definition_fr: 'Installation intermédiaire où les déchets sont déposés temporairement avant d\'être chargés sur de grands véhicules pour être transportés vers les installations de traitement ou d\'élimination.',
    definition_ar: 'منشأة وسيطة تُودَع فيها النفايات مؤقتاً قبل تحميلها على مركبات كبيرة لنقلها نحو منشآت المعالجة أو الإزالة.',
    reference: 'Loi n°01-19',
    classe: null,
  },
  {
    id: 47, categorie: 'installations',
    terme_fr: 'Unité de compostage',
    terme_ar: 'وحدة صنع السماد',
    definition_fr: 'Installation industrielle de traitement biologique des déchets organiques biodégradables (déchets verts, déchets alimentaires) en vue de produire du compost.',
    definition_ar: 'منشأة صناعية لمعالجة النفايات العضوية القابلة للتحلل (النفايات الخضراء، نفايات الطعام) بهدف إنتاج السماد.',
    reference: 'Décret n°06-104',
    classe: null,
  },
  {
    id: 48, categorie: 'installations',
    terme_fr: 'Unité de méthanisation',
    terme_ar: 'وحدة إنتاج الميثان',
    definition_fr: 'Installation de traitement anaérobie des déchets organiques permettant de produire du biogaz (méthane) utilisé comme source d\'énergie renouvelable, et un digestat utilisable comme engrais.',
    definition_ar: 'منشأة للمعالجة اللاهوائية للنفايات العضوية تتيح إنتاج الغاز الحيوي (الميثان) المستخدم كمصدر طاقة متجددة، وهضم يمكن استخدامه كسماد.',
    reference: 'Décret n°06-104',
    classe: null,
  },
]