# Generated by Django 4.2.13 on 2026-06-23 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrationEnvironnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_administration', models.CharField(choices=[('MINISTERE', "Ministère de l'Environnement et de la Qualité de la Vie"), ('DIR_WILAYA', "Direction de l'Environnement de Wilaya"), ('AND', 'Agence Nationale des Déchets (AND)')], max_length=20)),
                ('denomination', models.CharField(max_length=300)),
                ('wilaya', models.CharField(blank=True, max_length=3)),
                ('commune', models.CharField(blank=True, max_length=200)),
                ('adresse', models.TextField(blank=True)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('fax', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('site_web', models.URLField(blank=True)),
                ('nom_directeur', models.CharField(blank=True, max_length=200)),
                ('telephone_directeur', models.CharField(blank=True, max_length=30)),
                ('email_directeur', models.EmailField(blank=True, max_length=254)),
                ('numero_agrement_delivre', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif'), ('SUSPENDU', 'Suspendu')], default='ACTIF', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Administration de l'Environnement",
                'ordering': ['type_administration', 'wilaya', 'denomination'],
            },
        ),
    ]
