# Generated by Django 6.0.6 on 2026-06-23 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operateurs', '0001_initial'),
        ('recuperateurs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationRecuperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=30, unique=True)),
                ('bon_livraison', models.CharField(blank=True, max_length=100, verbose_name='Bon de livraison')),
                ('date_livraison', models.DateField(blank=True, null=True)),
                ('bon_commande', models.CharField(blank=True, max_length=100, verbose_name='Bon de commande n°')),
                ('commande_client', models.CharField(blank=True, max_length=200, verbose_name='Commande client')),
                ('date_commande', models.DateField(blank=True, null=True)),
                ('code_dechet', models.CharField(max_length=20)),
                ('designation_dechet', models.CharField(max_length=300)),
                ('classe_dechet', models.CharField(blank=True, max_length=5)),
                ('unite', models.CharField(choices=[('KG', 'Kilogramme (kg)'), ('TONNE', 'Tonne (t)'), ('M3', 'Mètre cube (m³)'), ('LITRE', 'Litre (L)'), ('UNITE', 'Unité')], default='KG', max_length=10)),
                ('quantite', models.DecimalField(decimal_places=3, max_digits=12)),
                ('chauffeur', models.CharField(blank=True, max_length=200)),
                ('immatriculation', models.CharField(blank=True, max_length=100)),
                ('date_recuperation', models.DateField(verbose_name='Date de récupération')),
                ('destination_type', models.CharField(choices=[('VALORISATION', 'Valorisation'), ('ELIMINATION', 'Élimination (DSD)'), ('STOCKAGE', 'Stockage temporaire'), ('RECYCLAGE', 'Recyclage')], default='VALORISATION', max_length=20)),
                ('bsd_numero', models.CharField(blank=True, max_length=100, verbose_name='N° BSD (si DSD)')),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], default='EN_COURS', max_length=15)),
                ('observations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('eliminateur', models.ForeignKey(blank=True, limit_choices_to={'type_operateur': 'ELIMINATEUR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_elimination', to='operateurs.operateur')),
                ('generateur', models.ForeignKey(blank=True, limit_choices_to={'type_operateur': 'GENERATEUR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_generateur', to='operateurs.operateur')),
                ('recuperateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='recuperateurs.recuperateur')),
                ('transporteur', models.ForeignKey(blank=True, limit_choices_to={'type_operateur': 'TRANSPORTEUR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_transport', to='operateurs.operateur')),
                ('valorisateur', models.ForeignKey(blank=True, limit_choices_to={'type_operateur': 'VALORISATEUR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_valorisation', to='operateurs.operateur')),
            ],
            options={
                'verbose_name': 'Opération de récupération',
                'ordering': ['-date_recuperation', '-created_at'],
            },
        ),
    ]
