// Nomenclature SARL Gold Environment Service — 140 codes (Décret 06-104)
// Source: Nomenclature_Agrement_Gold_Environment.xlsx
export const NOMENCLATURE_GOLD = [
  { code: '1.4.1', nom_fr: 'Boues et autres déchets de forage contenant des hydrocarbures', classe: 'SD', dangerosite: 'Inflammable, Toxique', annexe: 'I' },
  { code: '1.1.2', nom_fr: 'Boues provenant du lavage et du nettoyage', classe: 'S', dangerosite: '', annexe: 'II' },
  { code: '4.1.2', nom_fr: 'Déchets provenant de la sylviculture', classe: 'S', dangerosite: '', annexe: 'II' },
  { code: '5.1.2', nom_fr: 'Produits agrochimiques contenant des substances dangereuses', classe: 'SD', dangerosite: 'Dangereuse pour l\'environnement', annexe: 'I' },
  { code: '6.1.2', nom_fr: 'Produits agrochimiques autres que ceux visés à la rubrique 5.1.2', classe: 'S', dangerosite: '', annexe: 'II' },
  { code: '1.2.2', nom_fr: 'Boues provenant du lavage et du nettoyage', classe: 'S', dangerosite: '', annexe: 'II' },
  { code: '3.2.2', nom_fr: 'Matières impropres à la consommation ou à la transformation', classe: 'S', dangerosite: '', annexe: 'II' },
  { code: '4.2.2', nom_fr: 'Boues provenant du traitement in situ des effluents', classe: 'S', dangerosite: '', annexe: 'II' },
  { code: '1.3.2', nom_fr: 'Boues provenant du lavage, du nettoyage, de l\'épluchage, de la centrifugation et de la séparation', classe: 'S', dangerosite: '', annexe: 'II' },
  { code: '2.3.2', nom_fr: 'Déchets provenant des agents de conservation', classe: 'S', dangerosite: '', annexe: 'II' },
  { code: '3.3.2', nom_fr: 'Déchets provenant de l\'extraction par solvants', classe: 'S', dangerosite: '', annexe: 'II' },
  { code: '5.3.2', nom_fr: 'Boues provenant du traitement in situ des effluents', classe: 'S', dangerosite: '', annexe: 'II' },
  { code: '1.4.2', nom_fr: 'Carbonate de calcium déclassé', classe: 'S', dangerosite: '', annexe: 'II' },
  { code: '4.2', nom_fr: 'Boues provenant du traitement in situ des effluents', classe: 'S', dangerosite: '', annexe: 'II' },
  { code: '5.2', nom_fr: 'Boues provenant du traitement in situ des effluents', classe: 'S', dangerosite: '', annexe: 'II' },
  { code: '1.6.2', nom_fr: 'Matières impropres à la consommation ou à la transformation', classe: 'S', dangerosite: '', annexe: 'II' },
  { code: '2.6.2', nom_fr: 'Matières impropres à la consommation ou à la transformation', classe: 'S', dangerosite: '', annexe: 'II' },
  { code: '3.6.2', nom_fr: 'Boues provenant du traitement in situ des effluents', classe: 'S', dangerosite: '', annexe: 'II' },
  { code: '3.7.2', nom_fr: 'Boues provenant du traitement in situ des effluents', classe: 'S', dangerosite: '', annexe: 'II' },
  { code: '1.2.3', nom_fr: 'Composés organiques non halogénés de protection du bois', classe: 'SD', dangerosite: 'Comburante, Inflammable', annexe: 'I' },
  { code: '5.2.3', nom_fr: 'Autres produits de protection du bois contenant des substances dangereuses', classe: 'SD', dangerosite: 'Dangereuse pour l\'environnement', annexe: 'I' },
  { code: '2.3.3', nom_fr: 'Boues de désencrage provenant du recyclage du papier', classe: 'S', dangerosite: '', annexe: 'II' },
  { code: '3.3.3', nom_fr: 'Déchets de boues résiduaires', classe: 'S', dangerosite: '', annexe: 'II' },
  { code: '4.3.3', nom_fr: 'Déchets de fibres et boues de fibres provenant de la séparation mécanique', classe: 'S', dangerosite: '', annexe: 'II' },
  { code: '7.1.4', nom_fr: 'Boues provenant du traitement in situ des effluents, ne contenant pas de chrome', classe: 'S', dangerosite: '', annexe: 'II' },
  { code: '1.1.5', nom_fr: 'Boues de dessalage', classe: 'SD', dangerosite: 'Irritante', annexe: 'I' },
  { code: '2.1.5', nom_fr: 'Boues de fond de cuves', classe: 'SD', dangerosite: 'Dangereuse pour l\'environnement', annexe: 'I' },
  { code: '3.1.5', nom_fr: 'Boues d\'alkyles acides', classe: 'SD', dangerosite: 'Facilement inflammable, Toxique, Corrosive', annexe: 'I' },
  { code: '4.1.5', nom_fr: 'Hydrocarbures accidentellement répandus', classe: 'SD', dangerosite: 'Toxique, Cancérogène, Mutagène, Dangereuse pour l\'environnement', annexe: 'I' },
  { code: '5.1.5', nom_fr: 'Boues contenant des hydrocarbures provenant des opérations de maintenance des installations ou des équipements', classe: 'SD', dangerosite: 'Inflammable, Nocive', annexe: 'I' },
  { code: '6.1.5', nom_fr: 'Goudrons acides', classe: 'SD', dangerosite: 'Facilement inflammable, Toxique, Cancérogène, Mutagène', annexe: 'I' },
  { code: '8.1.5', nom_fr: 'Boues provenant du traitement in situ des effluents contenant des substances dangereuses', classe: 'SD', dangerosite: 'Dangereuse pour l\'environnement, Nocive', annexe: 'I' },
  { code: '10.1.5', nom_fr: 'Déchets provenant du nettoyage des hydrocarbures par les bases', classe: 'SD', dangerosite: 'Nocive', annexe: 'I' },
  { code: '11.1.5', nom_fr: 'Hydrocarbures contenant des acides', classe: 'SD', dangerosite: 'Toxique, Cancérogène, Mutagène, Dangereuse pour l\'environnement', annexe: 'I' },
  { code: '12.1.5', nom_fr: 'Boues provenant du traitement de l\'eau d\'alimentation des chaudières', classe: 'S', dangerosite: '', annexe: 'II' },
  { code: '13.1.5', nom_fr: 'Déchets provenant des colonnes de refroidissement', classe: 'S', dangerosite: '', annexe: 'II' },
  { code: '14.1.5', nom_fr: 'Argiles de filtration usagées', classe: 'SD', dangerosite: 'Toxique', annexe: 'I' },
  { code: '16.1.5', nom_fr: 'Mélange de résidus', classe: 'S', dangerosite: '', annexe: 'II' },
  { code: '1.1.6', nom_fr: 'Acide sulfurique et acide sulfureux', classe: 'SD', dangerosite: 'Comburante, Inflammable, Toxique, Corrosive, Irritante', annexe: 'I' },
  { code: '2.1.6', nom_fr: 'Acide chlorhydrique', classe: 'SD', dangerosite: 'Inflammable, Toxique, Corrosive, Irritante', annexe: 'I' },
  { code: '3.1.6', nom_fr: 'Acide fluorhydrique', classe: 'SD', dangerosite: 'Inflammable, Toxique, Corrosive, Irritante', annexe: 'I' },
  { code: '1.2.6', nom_fr: 'Hydroxyde de calcium', classe: 'SD', dangerosite: 'Nocive', annexe: 'I' },
  { code: '2.2.6', nom_fr: 'Hydroxyde d\'ammonium', classe: 'SD', dangerosite: 'Nocive, Comburante', annexe: 'I' },
  { code: '1.5.6', nom_fr: 'Boues provenant du traitement in situ des effluents contenant des substances dangereuses', classe: 'SD', dangerosite: 'Dangereuse pour l\'environnement', annexe: 'I' },
  { code: '1.12.6', nom_fr: 'Produits phytosanitaires inorganiques, agents de protection du bois et autres biocides', classe: 'SD', dangerosite: 'Toxique, Dangereuse pour l\'environnement', annexe: 'I' },
  { code: '2.12.6', nom_fr: 'Charbon actif usagé (sauf rubrique 2.7.6)', classe: 'SD', dangerosite: 'Inflammable, Toxique, Irritante', annexe: 'I' },
  { code: '3.12.6', nom_fr: 'Noir de carbone', classe: 'S', dangerosite: '', annexe: 'II' },
  { code: '1.4.7', nom_fr: 'Résidus de réaction et résidus de distillation halogénés', classe: 'SD', dangerosite: 'Toxique', annexe: 'I' },
  { code: '2.4.7', nom_fr: 'Résidus de réaction et résidus de distillation halogénés', classe: 'SD', dangerosite: 'Toxique', annexe: 'I' },
  { code: '3.4.7', nom_fr: 'Résidus de réaction et résidus de distillation halogénés', classe: 'SD', dangerosite: 'Toxique', annexe: 'I' },
  { code: '4.4.7', nom_fr: 'Résidus de réaction et résidus de distillation halogénés', classe: 'SD', dangerosite: 'Toxique', annexe: 'I' },
  { code: '10.4.7', nom_fr: 'Déchets solides contenant des substances dangereuses', classe: 'SD', dangerosite: 'Dangereuse pour l\'environnement', annexe: 'I' },
  { code: '4.5.7', nom_fr: 'Résidus de réaction et résidus de distillation halogénés', classe: 'SD', dangerosite: 'Toxique', annexe: 'I' },
  { code: '8.5.7', nom_fr: 'Boues provenant du traitement in situ des effluents contenant des substances dangereuses', classe: 'SD', dangerosite: 'Dangereuse pour l\'environnement', annexe: 'I' },
  { code: '4.6.7', nom_fr: 'Résidus de réaction et résidus de distillation halogénés', classe: 'SD', dangerosite: 'Toxique', annexe: 'I' },
  { code: '5.6.7', nom_fr: 'Autres résidus de réaction et de distillation', classe: 'SD', dangerosite: 'Toxique', annexe: 'I' },
  { code: '8.6.7', nom_fr: 'Boues provenant du traitement in situ des effluents contenant des substances dangereuses', classe: 'SD', dangerosite: 'Dangereuse pour l\'environnement', annexe: 'I' },
  { code: '4.7.7', nom_fr: 'Résidus de réaction et résidus de distillation halogénés', classe: 'SD', dangerosite: 'Toxique', annexe: 'I' },
  { code: '8.7.7', nom_fr: 'Boues provenant du traitement in situ des effluents contenant des substances dangereuses', classe: 'SD', dangerosite: 'Dangereuse pour l\'environnement', annexe: 'I' },
  { code: '1.8', nom_fr: 'Peintures et vernis autres que ceux visés à la rubrique 1.1.8', classe: 'S', dangerosite: '', annexe: 'II' },
  { code: '2.1.8', nom_fr: 'Déchets provenant du décapage des peintures ou des vernis autres que ceux visés à la rubrique 7.1.8', classe: 'S', dangerosite: '', annexe: 'II' },
  { code: '8.1.8', nom_fr: 'Boues aqueuses contenant de la peinture ou du vernis autres que ceux visés à la rubrique 9.1.8', classe: 'S', dangerosite: '', annexe: 'II' },
  { code: '2.2.8', nom_fr: 'Boues aqueuses contenant des substances dangereuses', classe: 'S', dangerosite: '', annexe: 'II' },
  { code: '2.1.10', nom_fr: 'Cendres volantes de charbon', classe: 'S', dangerosite: '', annexe: 'II' },
  { code: '3.1.10', nom_fr: 'Cendres volantes de tourbe et de bois non traité', classe: 'S', dangerosite: '', annexe: 'II' },
  { code: '4.1.10', nom_fr: 'Cendres volantes et cendres sous chaudière d\'hydrocarbures', classe: 'SD', dangerosite: 'Irritante, Toxique', annexe: 'I' },
  { code: '5.1.10', nom_fr: 'Déchets solides provenant des réactions basées sur le calcium pour la désulfuration des fumées', classe: 'S', dangerosite: '', annexe: 'II' },
  { code: '6.1.10', nom_fr: 'Boues des réactions basées sur le calcium pour la désulfuration des fumées', classe: 'S', dangerosite: '', annexe: 'II' },
  { code: '8.1.10', nom_fr: 'Cendres volantes provenant des hydrocarbures émulsifiés et utilisés comme combustibles', classe: 'SD', dangerosite: 'Toxique', annexe: 'I' },
  { code: '11.1.10', nom_fr: 'Cendres volantes issues de la co-incinération, contenant des substances dangereuses', classe: 'SD', dangerosite: 'Dangereuse pour l\'environnement', annexe: 'I' },
  { code: '15.1.10', nom_fr: 'Boues provenant du traitement in situ des effluents contenant des substances dangereuses', classe: 'SD', dangerosite: 'Toxique', annexe: 'I' },
  { code: '17.1.10', nom_fr: 'Boues aqueuses provenant du nettoyage des chaudières contenant des substances dangereuses', classe: 'SD', dangerosite: 'Toxique', annexe: 'I' },
  { code: '21.1.10', nom_fr: 'Déchets provenant du traitement des eaux de refroidissement', classe: 'S', dangerosite: '', annexe: 'II' },
  { code: '6.9.10', nom_fr: 'Poussières de filtration des fumées contenant des substances dangereuses', classe: 'SD', dangerosite: 'Dangereuse pour l\'environnement, Toxique', annexe: 'I' },
  { code: '10.9.10', nom_fr: 'Déchets de revêtement contenant des substances dangereuses', classe: 'SD', dangerosite: 'Dangereuse pour l\'environnement', annexe: 'I' },
  { code: '6.10.10', nom_fr: 'Poussières de filtration des fumées contenant des substances dangereuses', classe: 'SD', dangerosite: 'Dangereuse pour l\'environnement, Toxique', annexe: 'I' },
  { code: '4.8.10', nom_fr: 'Scories et crasses inflammables ou dégageant lors du contact avec l\'eau des gaz inflammables en quantités dangereuses', classe: 'SD', dangerosite: 'Toxique', annexe: 'I' },
  { code: '6.8.10', nom_fr: 'Déchets goudronneux provenant de la fabrication des anodes', classe: 'SD', dangerosite: 'Nocive', annexe: 'I' },
  { code: '9.8.10', nom_fr: 'Poussières de filtration des fumées contenant des substances dangereuses', classe: 'SD', dangerosite: 'Dangereuse pour l\'environnement', annexe: 'I' },
  { code: '11.8.10', nom_fr: 'Boues et gâteaux de filtration provenant de l\'épuration des fumées contenant des substances dangereuses', classe: 'SD', dangerosite: 'Dangereuse pour l\'environnement', annexe: 'I' },
  { code: '13.8.10', nom_fr: 'Déchets provenant du traitement des eaux de refroidissement contenant des hydrocarbures', classe: 'SD', dangerosite: 'Inflammable, Nocive', annexe: 'I' },
  { code: '2.2.10', nom_fr: 'Laitier non traité', classe: 'S', dangerosite: '', annexe: 'II' },
  { code: '3.2.10', nom_fr: 'Déchets solides provenant de l\'épuration des fumées contenant des substances dangereuses', classe: 'SD', dangerosite: 'Dangereuse pour l\'environnement', annexe: 'I' },
  { code: '4.1.11', nom_fr: 'Boues de phosphatation', classe: 'SD', dangerosite: 'Nocive', annexe: 'I' },
  { code: '5.1.11', nom_fr: 'Boues et gâteaux de filtration contenant des substances dangereuses', classe: 'SD', dangerosite: 'Dangereuse pour l\'environnement', annexe: 'I' },
  { code: '9.1.11', nom_fr: 'Déchets de dégraissage contenant des substances dangereuses', classe: 'SD', dangerosite: 'Dangereuse pour l\'environnement', annexe: 'I' },
  { code: '8.1.12', nom_fr: 'Émulsions et solutions d\'usinage sans halogènes', classe: 'SD', dangerosite: 'Nocive', annexe: 'I' },
  { code: '10.1.12', nom_fr: 'Déchets de cires et graisses', classe: 'SD', dangerosite: 'Nocive', annexe: 'I' },
  { code: '11.1.12', nom_fr: 'Déchets de brasage', classe: 'S', dangerosite: '', annexe: 'II' },
  { code: '12.1.12', nom_fr: 'Boues d\'usinage contenant des substances dangereuses', classe: 'SD', dangerosite: 'Dangereuse pour l\'environnement', annexe: 'I' },
  { code: '16.1.12', nom_fr: 'Boues métalliques (provenant du meulage et de l\'affûtage) contenant des hydrocarbures', classe: 'SD', dangerosite: 'Inflammable, Nocive', annexe: 'I' },
  { code: '1.4.13', nom_fr: 'Boues de fond de cuve provenant de la navigation fluviale', classe: 'SD', dangerosite: 'Inflammable, Irritante', annexe: 'I' },
  { code: '2.4.13', nom_fr: 'Boues de fond de cuve provenant des canaux des quais de port', classe: 'SD', dangerosite: 'Inflammable, Irritante', annexe: 'I' },
  { code: '3.4.13', nom_fr: 'Boues de fond de cuve provenant d\'autre type de navigation', classe: 'SD', dangerosite: 'Inflammable, Nocive', annexe: 'I' },
  { code: '2.5.13', nom_fr: 'Boues provenant des séparateurs eau/hydrocarbures', classe: 'SD', dangerosite: 'Nocive', annexe: 'I' },
  { code: '3.5.13', nom_fr: 'Boues provenant des déshuileurs', classe: 'SD', dangerosite: 'Nocive', annexe: 'I' },
  { code: '1.14', nom_fr: 'Solvants et mélanges de solvants halogénés autres', classe: 'SD', dangerosite: 'Dangereuse pour l\'environnement', annexe: 'I' },
  { code: '2.1.14', nom_fr: 'Solvants et mélanges de solvants halogénés autres', classe: 'SD', dangerosite: 'Dangereuse pour l\'environnement', annexe: 'I' },
  { code: '1.1.15', nom_fr: 'Absorbants, matériaux filtrants (y compris les filtres à huile non spécifiés ailleurs), chiffons d\'essuyage et vêtements de protection contaminés', classe: 'SD', dangerosite: 'Inflammable, Irritante, Nocive', annexe: 'I' },
  { code: '1.2.15', nom_fr: 'Absorbants, matériaux filtrants, chiffons d\'essuyage et vêtements de protection autres que ceux visés à la rubrique 1.2.15', classe: 'S', dangerosite: '', annexe: 'II' },
  { code: '2.2.15', nom_fr: 'Pneumatiques hors d\'usage', classe: 'S', dangerosite: '', annexe: 'II' },
  { code: '1.1.16', nom_fr: 'Déchets contenant des hydrocarbures', classe: 'SD', dangerosite: 'Inflammable, Toxique', annexe: 'I' },
  { code: '1.3.17', nom_fr: 'Mélanges bitumineux contenant du goudron', classe: 'SD', dangerosite: 'Inflammable, Toxique, Cancérogène, Mutagène', annexe: 'I' },
  { code: '3.3.17', nom_fr: 'Goudrons et produits goudronnés', classe: 'SD', dangerosite: 'Inflammable, Toxique, Cancérogène, Mutagène', annexe: 'I' },
  { code: '1.5.17', nom_fr: 'Terres et cailloux contenant des substances dangereuses', classe: 'SD', dangerosite: 'Dangereuse pour l\'environnement', annexe: 'I' },
  { code: '3.5.17', nom_fr: 'Boues de dragage contenant des substances dangereuses', classe: 'SD', dangerosite: 'Dangereuse pour l\'environnement', annexe: 'I' },
  { code: '1.7.17', nom_fr: 'Matériaux de construction à base de gypse contaminés par des substances dangereuses', classe: 'SD', dangerosite: 'Dangereuse pour l\'environnement', annexe: 'I' },
  { code: '2.1.19', nom_fr: 'Gâteaux de filtration provenant de l\'épuration des fumées', classe: 'SD', dangerosite: 'Toxique', annexe: 'I' },
  { code: '4.1.19', nom_fr: 'Déchets secs provenant de l\'épuration des fumées', classe: 'SD', dangerosite: 'Toxique', annexe: 'I' },
  { code: '7.1.19', nom_fr: 'Ferrailles non visées à la rubrique 6.1.19', classe: 'S', dangerosite: '', annexe: 'II' },
  { code: '8.1.19', nom_fr: 'Cendres volantes contenant des substances dangereuses', classe: 'SD', dangerosite: 'Dangereuse pour l\'environnement', annexe: 'I' },
  { code: '10.1.19', nom_fr: 'Cendres sous chaudière contenant des substances dangereuses', classe: 'SD', dangerosite: 'Dangereuse pour l\'environnement', annexe: 'I' },
  { code: '1.8.19', nom_fr: 'Déchets provenant du dégrillage', classe: 'S', dangerosite: '', annexe: 'II' },
  { code: '2.8.19', nom_fr: 'Déchets provenant du déssablage', classe: 'S', dangerosite: '', annexe: 'II' },
  { code: '3.8.19', nom_fr: 'Boues provenant du traitement des eaux urbaines résiduaires', classe: 'S', dangerosite: '', annexe: 'II' },
  { code: '10.8.19', nom_fr: 'Boues provenant du traitement biologique des effluents industriels autres que celles visées à la rubrique 9.8.19', classe: 'S', dangerosite: '', annexe: 'II' },
  { code: '12.8.19', nom_fr: 'Boues provenant d\'autres traitements des effluents industriels autres que celles visées à la rubrique 9.8', classe: 'S', dangerosite: '', annexe: 'II' },
  { code: '1.9.19', nom_fr: 'Déchets solides provenant de la filtration primaire et du dégrillage', classe: 'S', dangerosite: '', annexe: 'II' },
  { code: '2.9.19', nom_fr: 'Boues provenant de la clarification de l\'eau', classe: 'S', dangerosite: '', annexe: 'II' },
  { code: '3.9.19', nom_fr: 'Boues provenant de la décarbonatation', classe: 'S', dangerosite: '', annexe: 'II' },
  { code: '5.9.19', nom_fr: 'Résines échangeuses d\'ions saturées ou usées', classe: 'S', dangerosite: '', annexe: 'II' },
  { code: '6.9.19', nom_fr: 'Solutions et boues provenant de la régénération des échangeurs d\'ions', classe: 'S', dangerosite: '', annexe: 'II' },
  { code: '1.11.19', nom_fr: 'Argiles de filtration usagées', classe: 'SD', dangerosite: 'Facilement inflammable, Toxique, Cancérogène, Mutagène', annexe: 'I' },
  { code: '2.11.19', nom_fr: 'Goudrons acides', classe: 'SD', dangerosite: 'Facilement inflammable, Toxique, Cancérogène, Mutagène', annexe: 'I' },
  { code: '4.11.19', nom_fr: 'Déchets provenant du nettoyage des hydrocarbures par les bases', classe: 'SD', dangerosite: 'Toxique', annexe: 'I' },
  { code: '5.11.19', nom_fr: 'Boues provenant du traitement in situ des effluents contenant des substances dangereuses', classe: 'SD', dangerosite: 'Dangereuse pour l\'environnement', annexe: 'I' },
  { code: '7.11.19', nom_fr: 'Déchets provenant de l\'épuration des gaz de combustion', classe: 'S', dangerosite: '', annexe: 'II' },
  { code: '1.13.19', nom_fr: 'Déchets solides provenant de l\'assainissement des sols contenant des substances dangereuses', classe: 'SD', dangerosite: 'Toxique, Dangereuse pour l\'environnement', annexe: 'I' },
  { code: '3.13.19', nom_fr: 'Boues provenant de l\'assainissement des sols contenant des substances dangereuses', classe: 'SD', dangerosite: 'Dangereuse pour l\'environnement', annexe: 'I' },
  { code: '5.13.19', nom_fr: 'Boues provenant de l\'assainissement des eaux souterraines contenant des substances dangereuses', classe: 'SD', dangerosite: 'Toxique, Dangereuse pour l\'environnement', annexe: 'I' },
  { code: '1.1.20', nom_fr: 'Solvants', classe: 'SD', dangerosite: 'Inflammable, Irritante', annexe: 'I' },
  { code: '2.1.20', nom_fr: 'Acides', classe: 'SD', dangerosite: 'Inflammable, Irritante, Toxique', annexe: 'I' },
  { code: '3.1.20', nom_fr: 'Déchets des bases', classe: 'SD', dangerosite: 'Irritante, Toxique', annexe: 'I' },
  { code: '5.1.20', nom_fr: 'Pesticides (produits périmés non phosphatés et non chlorés)', classe: 'SD', dangerosite: 'Toxique, Dangereuse pour l\'environnement', annexe: 'I' },
  { code: '10.1.20', nom_fr: 'Peintures, encres, colles et résines contenant des substances dangereuses', classe: 'SD', dangerosite: 'Inflammable, Toxique', annexe: 'I' },
  { code: '11.1.20', nom_fr: 'Peintures, encres, colles et résines autres que celles visées à la rubrique 10.1.20', classe: 'S', dangerosite: '', annexe: 'II' },
  { code: '12.1.20', nom_fr: 'Détergents contenant des substances dangereuses', classe: 'SD', dangerosite: 'Inflammable, Irritante, Dangereuse pour l\'environnement', annexe: 'I' },
  { code: '22.1.20', nom_fr: 'Déchets provenant du nettoyage des conduits de cheminée', classe: 'S', dangerosite: '', annexe: 'II' },
  { code: '1.3.20', nom_fr: 'Boues de fossés d\'évacuation des eaux', classe: 'S', dangerosite: '', annexe: 'II' },
  { code: '2.3.20', nom_fr: 'Déchets provenant du nettoyage des canalisations d\'évacuation des eaux', classe: 'S', dangerosite: '', annexe: 'II' },
];