# Generated by Django 6.0.6 on 2026-06-23 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recuperateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialisation', models.TextField(blank=True, default='', help_text='Liste des sous-types de déchets sélectionnés, séparés par des virgules (ex: emb_plastique_pet,sp_huiles)')),
                ('numero_id', models.CharField(blank=True, max_length=30, unique=True)),
                ('type_recuperateur', models.CharField(choices=[('AVEC_AGREMENT', 'Avec agrément — Déchets Spéciaux / Dangereux'), ('SANS_AGREMENT', 'Sans agrément — Déchets ordinaires (MA/I)'), ('SANS_RC', 'Sans registre de commerce — Carte professionnelle')], max_length=20)),
                ('statut_juridique', models.CharField(blank=True, choices=[('EURL', 'EURL'), ('SARL', 'SARL'), ('SPA', 'SPA'), ('SNC', 'SNC'), ('PHYSIQUE', 'Personne physique'), ('AUTRE', 'Autre')], max_length=15)),
                ('nom_raison_sociale', models.CharField(max_length=300)),
                ('nom_commercial', models.CharField(blank=True, max_length=300)),
                ('responsable', models.CharField(max_length=200)),
                ('registre_commerce', models.CharField(blank=True, max_length=100)),
                ('nif', models.CharField(blank=True, max_length=50)),
                ('nis', models.CharField(blank=True, max_length=50)),
                ('num_carte_pro', models.CharField(blank=True, max_length=100)),
                ('adresse', models.TextField(blank=True)),
                ('wilaya', models.CharField(blank=True, max_length=3)),
                ('commune', models.CharField(blank=True, max_length=200)),
                ('code_postal', models.CharField(blank=True, max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('site_web', models.URLField(blank=True)),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('SUSPENDU', 'Suspendu'), ('EXPIRE', 'Expiré'), ('ARCHIVE', 'Archivé'), ('EN_ATTENTE', 'En attente de validation')], default='EN_ATTENTE', max_length=15)),
                ('date_creation', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recuperateur', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Récupérateur',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentRecuperateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_doc', models.CharField(choices=[('CARTE_PRO', 'Carte professionnelle'), ('AGREMENT', 'Agrément'), ('ASSURANCE', 'Assurance'), ('CONTRAT', 'Contrat'), ('AUTORISATION', 'Autorisation environnementale'), ('AUTRE', 'Autre')], max_length=20)),
                ('nom_fichier', models.CharField(max_length=200)),
                ('fichier', models.FileField(upload_to='recuperateurs/docs/')),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('recuperateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='recuperateurs.recuperateur')),
            ],
        ),
        migrations.CreateModel(
            name='AgrementRecuperateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_agrement', models.CharField(choices=[('AVEC_AGREMENT', 'Avec agrément'), ('SANS_AGREMENT', 'Sans agrément'), ('AUTRE', 'Autre')], default='AVEC_AGREMENT', max_length=20)),
                ('numero_agrement', models.CharField(blank=True, max_length=100)),
                ('date_delivrance', models.DateField(blank=True, null=True)),
                ('duree_validite_ans', models.IntegerField(blank=True, null=True, verbose_name='Durée validité (années)')),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('etendue_geo', models.CharField(choices=[('NATIONALE', 'Nationale'), ('WILAYA', 'Par wilaya'), ('WILAYAS', 'Multi-wilayas')], default='WILAYA', max_length=15)),
                ('wilayas_couvertes', models.TextField(blank=True, help_text='Codes wilaya séparés par virgule ex: 16,09,31')),
                ('codes_dechets', models.TextField(blank=True, help_text='Codes déchets autorisés séparés par virgule')),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('EXPIRE', 'Expiré'), ('SUSPENDU', 'Suspendu'), ('REVOQUE', 'Révoqué')], default='ACTIF', max_length=15)),
                ('autorite_delivrance', models.CharField(blank=True, max_length=200, verbose_name='Autorité de délivrance')),
                ('observations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recuperateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agrements', to='recuperateurs.recuperateur')),
            ],
            options={
                'verbose_name': 'Agrément',
                'ordering': ['-date_delivrance'],
            },
        ),
    ]
