# Generated by Django 4.2.13 on 2026-06-29 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recuperateurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recuperateur',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='recuperateurs/logos/'),
        ),
        migrations.AddField(
            model_name='recuperateur',
            name='numero_article',
            field=models.CharField(blank=True, max_length=50, verbose_name='N° Article (NA)'),
        ),
    ]
