# Generated by Django 6.0.6 on 2026-06-23 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recuperateurs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BordereauSuiviDechet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=30, unique=True)),
                ('generateur_nom', models.CharField(max_length=300)),
                ('generateur_adresse', models.TextField(blank=True)),
                ('transporteur_nom', models.CharField(blank=True, max_length=300)),
                ('recepteur_nom', models.CharField(blank=True, max_length=300)),
                ('code_dechet', models.CharField(max_length=20)),
                ('designation', models.CharField(max_length=300)),
                ('classe', models.CharField(blank=True, max_length=5)),
                ('quantite', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unite', models.CharField(default='KG', max_length=10)),
                ('date_emission', models.DateField()),
                ('date_reception', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EMIS', 'Émis'), ('EN_TRANSIT', 'En transit'), ('RECEPTIONNE', 'Réceptionné'), ('SIGNE', 'Signé'), ('ARCHIVE', 'Archivé')], default='BROUILLON', max_length=20)),
                ('signature_generateur', models.BooleanField(default=False)),
                ('signature_transporteur', models.BooleanField(default=False)),
                ('signature_recepteur', models.BooleanField(default=False)),
                ('observations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('recuperateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bsds', to='recuperateurs.recuperateur')),
            ],
            options={
                'verbose_name': 'BSD',
                'ordering': ['-created_at'],
            },
        ),
    ]
