# Generated by Django 4.2.13 on 2026-06-29 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bl', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonlivraison',
            name='bon_commande_numero',
        ),
        migrations.RemoveField(
            model_name='bonlivraison',
            name='camion_numero',
        ),
        migrations.RemoveField(
            model_name='bonlivraison',
            name='date_commande',
        ),
        migrations.RemoveField(
            model_name='bonlivraison',
            name='etabli_par',
        ),
        migrations.RemoveField(
            model_name='bonlivraison',
            name='garantie_alimentaire',
        ),
        migrations.RemoveField(
            model_name='bonlivraison',
            name='qualite',
        ),
    ]
