# Generated by Django 6.0.6 on 2026-06-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nomenclature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('famille', models.CharField(blank=True, max_length=10)),
                ('sous_famille', models.CharField(blank=True, max_length=20)),
                ('designation_fr', models.TextField()),
                ('designation_ar', models.TextField(blank=True)),
                ('classe', models.CharField(choices=[('MA', 'Ménagers et Assimilés'), ('I', 'Inertes'), ('S', 'Spéciaux'), ('SD', 'Spéciaux Dangereux')], max_length=5)),
                ('dangerosite_fr', models.TextField(blank=True)),
                ('dangerosite_ar', models.TextField(blank=True)),
                ('bsd_obligatoire', models.BooleanField(default=False)),
                ('agrement_requis', models.BooleanField(default=False)),
                ('conditions_stockage', models.TextField(blank=True)),
                ('conditions_transport', models.TextField(blank=True)),
                ('filieres_valorisation', models.TextField(blank=True)),
                ('filieres_elimination', models.TextField(blank=True)),
                ('explosible', models.BooleanField(default=False)),
                ('inflammable', models.BooleanField(default=False)),
                ('toxique', models.BooleanField(default=False)),
                ('cancerogene', models.BooleanField(default=False)),
                ('corrosive', models.BooleanField(default=False)),
                ('infectieuse', models.BooleanField(default=False)),
                ('dangereuse_environnement', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
    ]
