# Generated by Django 4.2.13 on 2026-06-23 22:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recuperateurs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.CharField(max_length=4)),
                ('date_transmission', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('SOUMISE', 'Soumise'), ('VALIDEE', 'Validee'), ('ARCHIVEE', 'Archivee')], default='BROUILLON', max_length=15)),
                ('denomination', models.CharField(blank=True, max_length=300)),
                ('statut_juridique', models.CharField(blank=True, max_length=20)),
                ('siege_social', models.TextField(blank=True)),
                ('domaine_activite', models.TextField(blank=True)),
                ('certification', models.CharField(blank=True, max_length=300)),
                ('responsable_dechets', models.CharField(blank=True, max_length=200)),
                ('matiere_premiere', models.TextField(blank=True)),
                ('denomination_dechet', models.TextField(blank=True)),
                ('code_dechet', models.CharField(blank=True, max_length=200)),
                ('consistance', models.CharField(blank=True, max_length=50)),
                ('autres_precisions', models.TextField(blank=True)),
                ('quantite_generee', models.CharField(blank=True, max_length=50)),
                ('composition_chimique', models.TextField(blank=True)),
                ('critere_dangerosite', models.TextField(blank=True)),
                ('stockage_temporaire_qte', models.CharField(blank=True, max_length=50)),
                ('stockage_permanent_qte', models.CharField(blank=True, max_length=50)),
                ('modalites_stockage', models.TextField(blank=True)),
                ('modalites_gestion', models.TextField(blank=True)),
                ('modalites_controle', models.TextField(blank=True)),
                ('modalites_elimination', models.TextField(blank=True)),
                ('types_installation', models.TextField(blank=True)),
                ('types_traitement', models.TextField(blank=True)),
                ('quantites_traitees', models.CharField(blank=True, max_length=50)),
                ('rendement_traitement', models.CharField(blank=True, max_length=100)),
                ('reutilisation_qte', models.CharField(default='0', max_length=50)),
                ('recyclage_qte', models.CharField(default='0', max_length=50)),
                ('valorisation_qte', models.CharField(default='0', max_length=50)),
                ('elimination_qte', models.CharField(default='0', max_length=50)),
                ('mesures_min_prises', models.TextField(blank=True)),
                ('mesures_min_envisager', models.TextField(blank=True)),
                ('mesures_bpe_prises', models.TextField(blank=True)),
                ('mesures_bpe_envisager', models.TextField(blank=True)),
                ('mesures_tech_prises', models.TextField(blank=True)),
                ('mesures_tech_envisager', models.TextField(blank=True)),
                ('mesures_pp_prises', models.TextField(blank=True)),
                ('mesures_pp_envisager', models.TextField(blank=True)),
                ('mesures_risques_prises', models.TextField(blank=True)),
                ('mesures_risques_envisager', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('recuperateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='declarations', to='recuperateurs.recuperateur')),
            ],
            options={
                'verbose_name': 'Declaration DSD',
                'ordering': ['-annee', '-created_at'],
            },
        ),
    ]
